In [2]:
import pandas as pd
import sqlite3

In [3]:
from pathlib import Path
db_path = Path().cwd().parent / 'data' / 'nba_stats.db'
print(db_path)
conn = sqlite3.connect(db_path)

tables = pd.read_sql("select * From sqlite_master where type='table'", conn)
tables['name'].to_list()

c:\Users\jorda\nba-model-hybrid\data\nba_stats.db

['player_defensive_stats',
 'team_defensive_stats',
 'player_hustle_stats',
 'team_hustle_stats',
 'player_miscellaneous_stats',
 'team_miscellaneous_stats',
 'team_basic_stats',
 'player_basic_stats',
 'player_info',
 'team_basic_stats_by_position',
 'team_advanced_stats_by_position',
 'team_scoring_stats_by_position',
 'player_shot_locations_boxscores',
 'defensive_stats_by_position_backup',
 'defensive_stats_by_position',
 'team_shot_location_boxscores',
 'predictions_2024_25',
 'predictions_all_models_2024_25',
 'predictions_multitask_model_2024_25',
 'predictions_multitask_model_2024_25_new',
 'team_aggregated_stats',
 'team_advanced_stats',
 'player_advanced_stats_v3',
 'team_advanced_stats_v3',
 'player_scoring_stats_v3',
 'team_scoring_stats_v3',
 'player_track_stats_v3',
 'team_track_stats_v3',
 'player_miscellaneous_stats_v3',
 'team_miscellaneous_stats_v3',
 'player_usage_stats_v3',
 'team_usage_stats_v3',
 'player_shot_location_boxscores',
 'nba_arenas',
 'nba_injury_logs',
 'sqlite_sequence',
 'nba_odds',
 'nba_odds_opening',
 'player_bpm',
 'predictions_log',
 'predictions_log_v2',
 'team_game_full']

In [10]:
 'player_basic_stats',
 'team_basic_stats',
 'player_advanced_stats_v3',
 'team_advanced_stats_v3',
 'player_scoring_stats_v3',
 'team_scoring_stats_v3',
 'player_track_stats_v3',
 'team_track_stats_v3',
 'player_miscellaneous_stats_v3',
 'team_miscellaneous_stats_v3',
 'player_usage_stats_v3',
 'team_usage_stats_v3',
 'team_shot_location_boxscores'
 'player_shot_location_boxscores'
 'player_hustle_stats',
 'team_hustle_stats',
 'defensive_stats_by_position',
 'player_info',
 'nba_odds'

'nba_odds'

In [6]:
# dsbp = pd.read_sql("select * from defensive_stats_by_position", conn)
# phs = pd.read_sql("select * from player_hustle_stats", conn)
# ths = pd.read_sql("select * from team_hustle_stats", conn)
pslb = pd.read_sql("select * from player_shot_location_boxscores", conn)
pus = pd.read_sql("select * from player_usage_stats_v3", conn)

# display(phs)
# display(ths)
display(tus)

NameError: name 'tus' is not defined

In [60]:
pslb

,personId,playerName,teamId,teamTricode,AGE,NICKNAME,Restricted Area FGM,Restricted Area FGA,Restricted Area FG_PCT,In The Paint (Non-RA) FGM,...,Above the Break 3 FGA,Above the Break 3 FG_PCT,Backcourt FGM,Backcourt FGA,Backcourt FG_PCT,Corner 3 FGM,Corner 3 FGA,Corner 3 FG_PCT,season,gameDate
0,203094,Andrew Nicholson,1610612753,ORL,24.0,Andrew,2.0,3.0,0.667,0.0,...,0.0,0.000,0.0,0.0,0.0,2.0,2.0,1.0,2013-14,2013-10-29
1,201167,Arron Afflalo,1610612753,ORL,28.0,Arron,1.0,2.0,0.500,0.0,...,4.0,0.250,0.0,1.0,0.0,0.0,0.0,0.0,2013-14,2013-10-29
2,201933,Blake Griffin,1610612746,LAC,25.0,Blake,7.0,9.0,0.778,1.0,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2013-14,2013-10-29
3,201228,C.J. Watson,1610612754,IND,30.0,C.J.,1.0,1.0,1.000,0.0,...,2.0,0.000,0.0,0.0,0.0,1.0,2.0,0.5,2013-14,2013-10-29
4,2430,Carlos Boozer,1610612741,CHI,32.0,Carlos,10.0,12.0,0.833,1.0,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2013-14,2013-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339155,1642383,Walter Clayton Jr.,1610612762,UTA,22.0,Walter,0.0,1.0,0.000,0.0,...,5.0,0.400,0.0,0.0,0.0,0.0,0.0,0.0,2025-26,2026-01-03
339156,1642954,Will Richard,1610612744,GSW,23.0,Will,1.0,1.0,1.000,0.0,...,3.0,0.333,0.0,0.0,0.0,1.0,1.0,1.0,2025-26,2026-01-03
339157,1642905,Yang Hansen,1610612757,POR,20.0,ang Hansen,0.0,1.0,0.000,0.0,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2025-26,2026-01-03
339158,1642949,Yanic Konan Niederhäuser,1610612746,LAC,22.0,Yanic Konan,0.0,0.0,0.000,0.0,...,0.0,0.000,NaN,NaN,NaN,0.0,0.0,0.0,2025-26,2026-01-03
339159,1642258,Zaccharie Risacher,1610612737,ATL,20.0,Zaccharie,1.0,3.0,0.333,1.0,...,3.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2025-26,2026-01-03

In [10]:
pd.read_sql("select * from team_miscellaneous_stats_v3", conn)

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,minutes,pointsOffTurnovers,pointsSecondChance,pointsFastBreak,pointsPaint,oppPointsOffTurnovers,oppPointsSecondChance,oppPointsFastBreak,oppPointsPaint,blocks,blocksAgainst,foulsPersonal,foulsDrawn
0,0041300405,1610612759,San Antonio,Spurs,SAS,spurs,240:00,12,5,16,32,8,8,11,34,4,4,21,23
1,0041300405,1610612748,Miami,Heat,MIA,heat,240:00,8,8,11,34,12,5,16,32,4,4,23,21
2,0041300404,1610612748,Miami,Heat,MIA,heat,240:00,21,10,7,30,12,11,6,46,1,4,25,19
3,0041300404,1610612759,San Antonio,Spurs,SAS,spurs,240:00,12,11,6,46,21,10,7,30,4,1,19,25
4,0041300403,1610612748,Miami,Heat,MIA,heat,240:00,6,4,4,42,23,6,12,48,1,4,26,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5029,0021401043,1610612765,Detroit,Pistons,DET,pistons,265:00,6,10,15,44,11,18,4,42,10,5,21,23
5030,0021400633,1610612764,Washington,Wizards,WAS,wizards,265:00,11,12,21,48,10,10,20,56,3,5,20,21
5031,0021400633,1610612760,Oklahoma City,Thunder,OKC,thunder,265:00,10,10,20,56,11,12,21,48,5,3,21,20
5032,0021400054,1610612740,New Orleans,Pelicans,NOP,pelicans,240:00,12,14,8,48,20,4,11,36,6,1,19,15
5033,0021400054,1610612766,Charlotte,Hornets,CHA,hornets,240:00,20,4,11,36,12,14,8,48,1,6,15,19

In [86]:
df = pd.read_sql("select * from team_game_full", conn)

ProgrammingError: Cannot operate on a closed database.

Empty DataFrame
Columns: [seasonYear, teamId, teamTricode, gameId, gameDate, MATCHUP, WL, minutes, points, plusMinus, fieldGoalsMade, fieldGoalsAttempted, fieldGoalPercentage, threePointersMade, threePointersAttempted, threePointerPercentage, freeThrowsMade, freeThrowsAttempted, freeThrowPercentage, offensiveRebounds, defensiveRebounds, rebounds, assists, steals, blocks, turnovers, personalFouls, offensiveRating, defensiveRating, netRating, assistPercentage, assistToTurnover, assistRatio, offensiveReboundPercentage, defensiveReboundPercentage, reboundPercentage, effectiveFieldGoalPercentage, trueShootingPercentage, usagePercentage, pace, PIE, percentageFieldGoalsAttempted2pt, percentageFieldGoalsAttempted3pt, percentagePoints2pt, percentagePointsMidrange2pt, percentagePoints3pt, percentagePointsFastBreak, percentagePointsFreeThrow, percentagePointsOffTurnovers, percentagePointsPaint, percentageAssisted2pt, percentageUnassisted2pt, percentageAssisted3pt, percentageUnassisted3pt, percentageAssistedFGM, percentageUnassistedFGM, distance, touches, secondaryAssists, freeThrowAssists, passes, contestedFieldGoalsMade, contestedFieldGoalsAttempted, contestedFieldGoalPercentage, uncontestedFieldGoalsMade, uncontestedFieldGoalsAttempted, uncontestedFieldGoalsPercentage, defendedAtRimFieldGoalsMade, defendedAtRimFieldGoalsAttempted, defendedAtRimFieldGoalPercentage, reboundChancesOffensive, reboundChancesDefensive, reboundChancesTotal, contestedShots, contestedShots2pt, contestedShots3pt, deflections, chargesDrawn, screenAssists, screenAssistPoints, looseBallsRecoveredOffensive, looseBallsRecoveredDefensive, looseBallsRecoveredTotal, offensiveBoxOuts, defensiveBoxOuts, boxOutPlayerTeamRebounds, boxOutPlayerRebounds, boxOuts, Restricted Area FGM, Restricted Area FGA, Restricted Area FG_PCT, In The Paint (Non-RA) FGM, In The Paint (Non-RA) FGA, In The Paint (Non-RA) FG_PCT, Mid-Range FGM, Mid-Range FGA, Mid-Range FG_PCT, Above the Break 3 FGM, Above the Break 3 FGA, Above the Break 3 FG_PCT, ...]
Index: []

[0 rows x 166 columns]

In [20]:
from sbrscrape import Scoreboard

sb = Scoreboard(sport='NBA', date='2019-10-22', current_line=False)

In [21]:
pd.DataFrame(sb.games)

,date,status,home_team,home_team_loc,home_team_abbr,home_team_rank,away_team,away_team_loc,away_team_abbr,away_team_rank,...,away_score,home_spread,home_spread_odds,away_spread,away_spread_odds,under_odds,over_odds,total,home_ml,away_ml
0,2019-10-23T00:00:00+00:00,Final OT,Toronto Raptors,Toronto,TOR,-1,New Orleans Pelicans,New Orleans,NO,-1,...,122,"{'betmgm': -5.5, 'fanduel': -5.5, 'caesars': -...","{'betmgm': -110, 'fanduel': -110, 'caesars': -...","{'betmgm': 5.5, 'fanduel': 5.5, 'caesars': 7, ...","{'betmgm': -110, 'fanduel': -110, 'caesars': -...","{'betmgm': 100, 'fanduel': -110, 'caesars': -1...","{'betmgm': -120, 'fanduel': -110, 'caesars': -...","{'betmgm': 226.5, 'fanduel': 232.5, 'caesars':...","{'betmgm': -238, 'fanduel': -240, 'caesars': -...","{'betmgm': 190, 'fanduel': 198, 'caesars': 245..."
1,2019-10-23T02:30:00+00:00,Final,Los Angeles Clippers,L.A. Clippers,LAC,-1,Los Angeles Lakers,L.A. Lakers,LAL,-1,...,102,"{'betmgm': -1.5, 'fanduel': -1, 'bet365': -1, ...","{'betmgm': -105, 'fanduel': -110, 'bet365': -1...","{'betmgm': 1.5, 'fanduel': 1, 'bet365': 1, 'dr...","{'betmgm': -115, 'fanduel': -110, 'bet365': -1...","{'betmgm': 100, 'fanduel': -110, 'bet365': -11...","{'betmgm': -120, 'fanduel': -110, 'bet365': -1...","{'betmgm': 226.5, 'fanduel': 226.5, 'bet365': ...","{'betmgm': -115, 'fanduel': -114, 'bet365': 10...","{'betmgm': -105, 'fanduel': -102, 'bet365': -1..."

In [25]:
training_set = pd.read_csv('../data/processed/training_set_v1.csv')

training_set

,teamId_home,gameDate,seasonYear,gameId,off_fieldGoalsMade_5g_home,off_fieldGoalsMade_20g_home,off_fieldGoalsMade_40g_home,off_fieldGoalsAttempted_5g_home,off_fieldGoalsAttempted_20g_home,off_fieldGoalsAttempted_40g_home,...,games_last_7d_away,season_game_number_away,is_playoff_away,matchup_away,wl_away,points_away,is_home_away,target_home_win,target_point_diff,target_total_pts
0,1610612737,2013-11-01,2013-14,21300023,37.000000,37.000000,37.000000,76.000000,76.000000,76.000000,...,1.0,2,0,TOR @ ATL,L,95,0,1,7,197
1,1610612737,2013-11-09,2013-14,21300086,40.213270,39.303937,39.151118,86.691943,84.399624,84.000201,...,3.0,7,0,ORL @ ATL,L,94,0,1,10,198
2,1610612737,2013-11-13,2013-14,21300116,39.025255,39.122448,39.070195,83.687227,83.769509,83.621490,...,2.0,7,0,NYK @ ATL,W,95,0,0,-4,186
3,1610612737,2013-11-15,2013-14,21300127,37.629025,38.409862,38.468058,81.367645,82.599365,82.641920,...,4.0,10,0,PHI @ ATL,L,103,0,1,10,216
4,1610612737,2013-11-20,2013-14,21300166,37.705784,38.428550,38.499802,78.070817,80.591687,80.965272,...,3.0,11,0,DET @ ATL,L,85,0,1,8,178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15464,1610612766,2025-03-25,2024-25,22401045,40.125124,39.355698,38.855261,85.951989,88.551092,89.020886,...,3.0,973,0,ORL @ CHA,W,111,0,0,-7,215
15465,1610612766,2025-03-31,2024-25,22401089,36.703740,38.440852,38.445687,90.170960,89.383214,89.396207,...,3.0,1009,0,UTA @ CHA,L,106,0,1,4,216
15466,1610612766,2025-04-04,2024-25,22401118,39.534996,39.077432,38.781612,83.853760,87.490567,88.404301,...,3.0,968,0,SAC @ CHA,W,125,0,0,-23,227
15467,1610612766,2025-04-06,2024-25,22401133,37.356664,38.498629,38.499583,83.569173,87.062894,88.140677,...,3.0,985,0,CHI @ CHA,W,131,0,0,-14,248
15468,1610612766,2025-04-08,2024-25,22401146,38.571109,38.736855,38.621554,84.046115,86.866428,87.987473,...,3.0,1016,0,MEM @ CHA,W,124,0,0,-24,224

In [32]:
training_set

,teamId_home,gameDate,seasonYear,gameId,off_fieldGoalsMade_5g_home,off_fieldGoalsMade_20g_home,off_fieldGoalsMade_40g_home,off_fieldGoalsAttempted_5g_home,off_fieldGoalsAttempted_20g_home,off_fieldGoalsAttempted_40g_home,...,games_last_7d_away,season_game_number_away,is_playoff_away,matchup_away,wl_away,points_away,is_home_away,target_home_win,target_point_diff,target_total_pts
0,1610612737,2013-11-01,2013-14,21300023,37.000000,37.000000,37.000000,76.000000,76.000000,76.000000,...,1.0,2,0,TOR @ ATL,L,95,0,1,7,197
1,1610612737,2013-11-09,2013-14,21300086,40.213270,39.303937,39.151118,86.691943,84.399624,84.000201,...,3.0,7,0,ORL @ ATL,L,94,0,1,10,198
2,1610612737,2013-11-13,2013-14,21300116,39.025255,39.122448,39.070195,83.687227,83.769509,83.621490,...,2.0,7,0,NYK @ ATL,W,95,0,0,-4,186
3,1610612737,2013-11-15,2013-14,21300127,37.629025,38.409862,38.468058,81.367645,82.599365,82.641920,...,4.0,10,0,PHI @ ATL,L,103,0,1,10,216
4,1610612737,2013-11-20,2013-14,21300166,37.705784,38.428550,38.499802,78.070817,80.591687,80.965272,...,3.0,11,0,DET @ ATL,L,85,0,1,8,178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15464,1610612766,2025-03-25,2024-25,22401045,40.125124,39.355698,38.855261,85.951989,88.551092,89.020886,...,3.0,973,0,ORL @ CHA,W,111,0,0,-7,215
15465,1610612766,2025-03-31,2024-25,22401089,36.703740,38.440852,38.445687,90.170960,89.383214,89.396207,...,3.0,1009,0,UTA @ CHA,L,106,0,1,4,216
15466,1610612766,2025-04-04,2024-25,22401118,39.534996,39.077432,38.781612,83.853760,87.490567,88.404301,...,3.0,968,0,SAC @ CHA,W,125,0,0,-23,227
15467,1610612766,2025-04-06,2024-25,22401133,37.356664,38.498629,38.499583,83.569173,87.062894,88.140677,...,3.0,985,0,CHI @ CHA,W,131,0,0,-14,248
15468,1610612766,2025-04-08,2024-25,22401146,38.571109,38.736855,38.621554,84.046115,86.866428,87.987473,...,3.0,1016,0,MEM @ CHA,W,124,0,0,-24,224

In [30]:
[x for x in training_set.columns if 'rest' in x]
training_set['days_rest_home'].value_counts()

days_rest_home
2.0      9783
3.0      2461
1.0      2084
4.0       552
5.0       112
         ...
103.0       1
159.0       1
193.0       1
184.0       1
155.0       1
Name: count, Length: 81, dtype: int64

In [44]:
team_id = 1610612737
cols = ['gameDate', 'seasonYear', 'off_plusMinus_5g_home', 'points_home', 'points_away', 'target_point_diff']
training_set.loc[training_set['teamId_home'] == team_id][cols]

,gameDate,seasonYear,off_plusMinus_5g_home,points_home,points_away,target_point_diff
0,2013-11-01,2013-14,-9.000000,102,95,7
1,2013-11-09,2013-14,0.284360,104,94,10
2,2013-11-13,2013-14,5.663429,91,95,-4
3,2013-11-15,2013-14,2.311499,113,103,10
4,2013-11-20,2013-14,1.265387,93,85,8
...,...,...,...,...,...,...
508,2025-04-01,2024-25,6.578191,113,127,-14
509,2025-04-05,2024-25,-0.854137,105,121,-16
510,2025-04-06,2024-25,-5.902758,147,134,13
511,2025-04-13,2024-25,9.080937,117,105,12
512,2025-04-18,2024-25,-1.630695,114,123,-9

In [42]:

print(training_set.columns[:100])

Index(['teamId_home', 'gameDate', 'seasonYear', 'gameId',
       'off_fieldGoalsMade_5g_home', 'off_fieldGoalsMade_20g_home',
       'off_fieldGoalsMade_40g_home', 'off_fieldGoalsAttempted_5g_home',
       'off_fieldGoalsAttempted_20g_home', 'off_fieldGoalsAttempted_40g_home',
       'off_fieldGoalPercentage_5g_home', 'off_fieldGoalPercentage_20g_home',
       'off_fieldGoalPercentage_40g_home', 'off_threePointersMade_5g_home',
       'off_threePointersMade_20g_home', 'off_threePointersMade_40g_home',
       'off_threePointersAttempted_5g_home',
       'off_threePointersAttempted_20g_home',
       'off_threePointersAttempted_40g_home',
       'off_threePointerPercentage_5g_home',
       'off_threePointerPercentage_20g_home',
       'off_threePointerPercentage_40g_home', 'off_freeThrowsMade_5g_home',
       'off_freeThrowsMade_20g_home', 'off_freeThrowsMade_40g_home',
       'off_freeThrowsAttempted_5g_home', 'off_freeThrowsAttempted_20g_home',
       'off_freeThrowsAttempted_40g_home', 'off_freeThrowPercentage_5g_home',
       'off_freeThrowPercentage_20g_home', 'off_freeThrowPercentage_40g_home',
       'off_offensiveRebounds_5g_home', 'off_offensiveRebounds_20g_home',
       'off_offensiveRebounds_40g_home', 'off_defensiveRebounds_5g_home',
       'off_defensiveRebounds_20g_home', 'off_defensiveRebounds_40g_home',
       'off_rebounds_5g_home', 'off_rebounds_20g_home',
       'off_rebounds_40g_home', 'off_assists_5g_home', 'off_assists_20g_home',
       'off_assists_40g_home', 'off_steals_5g_home', 'off_steals_20g_home',
       'off_steals_40g_home', 'off_blocks_5g_home', 'off_blocks_20g_home',
       'off_blocks_40g_home', 'off_turnovers_5g_home',
       'off_turnovers_20g_home', 'off_turnovers_40g_home',
       'off_personalFouls_5g_home', 'off_personalFouls_20g_home',
       'off_personalFouls_40g_home', 'off_points_5g_home',
       'off_points_20g_home', 'off_points_40g_home', 'off_plusMinus_5g_home',
       'off_plusMinus_20g_home', 'off_plusMinus_40g_home',
       'off_offensiveRating_5g_home', 'off_offensiveRating_20g_home',
       'off_offensiveRating_40g_home', 'off_defensiveRating_5g_home',
       'off_defensiveRating_20g_home', 'off_defensiveRating_40g_home',
       'off_netRating_5g_home', 'off_netRating_20g_home',
       'off_netRating_40g_home', 'off_assistPercentage_5g_home',
       'off_assistPercentage_20g_home', 'off_assistPercentage_40g_home',
       'off_assistToTurnover_5g_home', 'off_assistToTurnover_20g_home',
       'off_assistToTurnover_40g_home', 'off_assistRatio_5g_home',
       'off_assistRatio_20g_home', 'off_assistRatio_40g_home',
       'off_offensiveReboundPercentage_5g_home',
       'off_offensiveReboundPercentage_20g_home',
       'off_offensiveReboundPercentage_40g_home',
       'off_defensiveReboundPercentage_5g_home',
       'off_defensiveReboundPercentage_20g_home',
       'off_defensiveReboundPercentage_40g_home',
       'off_reboundPercentage_5g_home', 'off_reboundPercentage_20g_home',
       'off_reboundPercentage_40g_home', 'off_contestedShots_5g_home',
       'off_contestedShots_20g_home', 'off_contestedShots_40g_home',
       'off_contestedShots2pt_5g_home', 'off_contestedShots2pt_20g_home',
       'off_contestedShots2pt_40g_home', 'off_contestedShots3pt_5g_home',
       'off_contestedShots3pt_20g_home', 'off_contestedShots3pt_40g_home',
       'off_deflections_5g_home', 'off_deflections_20g_home',
       'off_deflections_40g_home'],
      dtype='object')

In [46]:
betting_df = pd.read_csv('../data/processed/backtest_predictions.csv')

In [53]:
betting_df[['gameDate', 'prob_home_win', 'odds_home_ml', 'odds_home_ml_open', 'target_home_win']]

,gameDate,prob_home_win,odds_home_ml,odds_home_ml_open,target_home_win
0,2019-10-22,0.792380,-5000.0,-215.0,1
1,2019-10-22,0.533707,-2500.0,-121.0,1
2,2019-10-23,0.791076,-175.0,-121.0,1
3,2019-10-23,0.654431,-3335.0,-345.0,1
4,2019-10-23,0.696729,-1250.0,-345.0,1
...,...,...,...,...,...
7585,2025-06-11,0.386851,145.0,164.0,1
7586,2025-06-13,0.371972,220.0,195.0,0
7587,2025-06-16,0.718828,-360.0,-375.0,1
7588,2025-06-19,0.329630,180.0,195.0,1
7589,2025-06-22,0.695523,-265.0,-355.0,1

In [1]:
from sbrscrape import Scoreboard

sb = Scoreboard(sport='NBA', date='2019-10-22')

In [2]:
sb.games

[{'date': '2019-10-23T00:00:00+00:00',
  'status': 'Final OT',
  'home_team': 'Toronto Raptors',
  'home_team_loc': 'Toronto',
  'home_team_abbr': 'TOR',
  'home_team_rank': -1,
  'away_team': 'New Orleans Pelicans',
  'away_team_loc': 'New Orleans',
  'away_team_abbr': 'NO',
  'away_team_rank': -1,
  'home_score': 130,
  'away_score': 122,
  'home_spread': {'betmgm': -12.5,
   'fanduel': -3.5,
   'caesars': -7,
   'bet365': -6.5,
   'draftkings': -1.5},
  'home_spread_odds': {'betmgm': 200,
   'fanduel': 104,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -121},
  'away_spread': {'betmgm': 12.5,
   'fanduel': 3.5,
   'caesars': 7,
   'bet365': 6.5,
   'draftkings': 1.5},
  'away_spread_odds': {'betmgm': -250,
   'fanduel': -132,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -108},
  'under_odds': {'betmgm': -110,
   'fanduel': -128,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -112},
  'over_odds': {'betmgm': -110,
   'fanduel': 100,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -115},
  'total': {'betmgm': 229.5,
   'fanduel': 234.5,
   'caesars': 229,
   'bet365': 229.5,
   'draftkings': 232.5},
  'home_ml': {'betmgm': -294,
   'fanduel': -1800,
   'caesars': -290,
   'bet365': -290,
   'draftkings': -5000},
  'away_ml': {'betmgm': 230,
   'fanduel': 800,
   'caesars': 245,
   'bet365': 235,
   'draftkings': 1500}},
 {'date': '2019-10-23T02:30:00+00:00',
  'status': 'Final',
  'home_team': 'Los Angeles Clippers',
  'home_team_loc': 'L.A. Clippers',
  'home_team_abbr': 'LAC',
  'home_team_rank': -1,
  'away_team': 'Los Angeles Lakers',
  'away_team_loc': 'L.A. Lakers',
  'away_team_abbr': 'LAL',
  'away_team_rank': -1,
  'home_score': 112,
  'away_score': 102,
  'home_spread': {'betmgm': 3.5,
   'fanduel': -9.5,
   'bet365': 3.5,
   'draftkings': -7},
  'home_spread_odds': {'betmgm': -115,
   'fanduel': -132,
   'bet365': -105,
   'draftkings': -114},
  'away_spread': {'betmgm': -3.5,
   'fanduel': 9.5,
   'bet365': -3.5,
   'draftkings': 7},
  'away_spread_odds': {'betmgm': -105,
   'fanduel': 104,
   'bet365': -115,
   'draftkings': -113},
  'under_odds': {'betmgm': -105,
   'fanduel': -112,
   'bet365': -110,
   'draftkings': -152},
  'over_odds': {'betmgm': -115,
   'fanduel': -112,
   'bet365': -110,
   'draftkings': 117},
  'total': {'betmgm': 222.5,
   'fanduel': 218.5,
   'bet365': 224.5,
   'draftkings': 219.5},
  'home_ml': {'betmgm': 140,
   'fanduel': -1600,
   'bet365': 150,
   'draftkings': -2500},
  'away_ml': {'betmgm': -167,
   'fanduel': 750,
   'bet365': -170,
   'draftkings': 1150}}]

In [5]:
import pandas as pd
odds_archive =pd.read_csv("../data/nba_odds_archive.csv")

In [6]:
odds_archive.columns

Index(['season', 'date', 'home_team', 'away_team', 'home_1stQtr',
       'away_1stQtr', 'home_2ndQtr', 'away_2ndQtr', 'home_3rdQtr',
       'away_3rdQtr', 'home_4thQtr', 'away_4thQtr', 'home_final', 'away_final',
       'home_close_ml', 'away_close_ml', 'home_open_spread',
       'away_open_spread', 'home_close_spread', 'away_close_spread',
       'home_2H_spread', 'away_2H_spread', '2H_total', 'open_over_under',
       'close_over_under'],
      dtype='object')

In [ ]:
--- Table: player_basic_stats ---
Columns: ['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'AVAILABLE_FLAG', 'MIN_SEC']

--- Table: player_advanced_stats_v3 ---
Columns: ['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'estimatedOffensiveRating', 'offensiveRating', 'estimatedDefensiveRating', 'defensiveRating', 'estimatedNetRating', 'netRating', 'assistPercentage', 'assistToTurnover', 'assistRatio', 'offensiveReboundPercentage', 'defensiveReboundPercentage', 'reboundPercentage', 'turnoverRatio', 'effectiveFieldGoalPercentage', 'trueShootingPercentage', 'usagePercentage', 'estimatedUsagePercentage', 'estimatedPace', 'pace', 'pacePer40', 'possessions', 'PIE']

--- Table: player_scoring_stats_v3 ---
Columns: ['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'percentageFieldGoalsAttempted2pt', 'percentageFieldGoalsAttempted3pt', 'percentagePoints2pt', 'percentagePointsMidrange2pt', 'percentagePoints3pt', 'percentagePointsFastBreak', 'percentagePointsFreeThrow', 'percentagePointsOffTurnovers', 'percentagePointsPaint', 'percentageAssisted2pt', 'percentageUnassisted2pt', 'percentageAssisted3pt', 'percentageUnassisted3pt', 'percentageAssistedFGM', 'percentageUnassistedFGM']

--- Table: player_track_stats_v3 ---
Columns: ['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'speed', 'distance', 'reboundChancesOffensive', 'reboundChancesDefensive', 'reboundChancesTotal', 'touches', 'secondaryAssists', 'freeThrowAssists', 'passes', 'assists', 'contestedFieldGoalsMade', 'contestedFieldGoalsAttempted', 'contestedFieldGoalPercentage', 'uncontestedFieldGoalsMade', 'uncontestedFieldGoalsAttempted', 'uncontestedFieldGoalsPercentage', 'fieldGoalPercentage', 'defendedAtRimFieldGoalsMade', 'defendedAtRimFieldGoalsAttempted', 'defendedAtRimFieldGoalPercentage']

--- Table: player_usage_stats_v3 ---
Columns: ['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'usagePercentage', 'percentageFieldGoalsMade', 'percentageFieldGoalsAttempted', 'percentageThreePointersMade', 'percentageThreePointersAttempted', 'percentageFreeThrowsMade', 'percentageFreeThrowsAttempted', 'percentageReboundsOffensive', 'percentageReboundsDefensive', 'percentageReboundsTotal', 'percentageAssists', 'percentageTurnovers', 'percentageSteals', 'percentageBlocks', 'percentageBlocksAllowed', 'percentagePersonalFouls', 'percentagePersonalFoulsDrawn', 'percentagePoints']

--- Table: player_shot_location_boxscores ---
Columns: ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'NICKNAME', 'Restricted Area FGM', 'Restricted Area FGA', 'Restricted Area FG_PCT', 'In The Paint (Non-RA) FGM', 'In The Paint (Non-RA) FGA', 'In The Paint (Non-RA) FG_PCT', 'Mid-Range FGM', 'Mid-Range FGA', 'Mid-Range FG_PCT', 'Left Corner 3 FGM', 'Left Corner 3 FGA', 'Left Corner 3 FG_PCT', 'Right Corner 3 FGM', 'Right Corner 3 FGA', 'Right Corner 3 FG_PCT', 'Above the Break 3 FGM', 'Above the Break 3 FGA', 'Above the Break 3 FG_PCT', 'Backcourt FGM', 'Backcourt FGA', 'Backcourt FG_PCT', 'Corner 3 FGM', 'Corner 3 FGA', 'Corner 3 FG_PCT', 'SEASON', 'GAME_DATE']

--- Table: player_hustle_stats ---
Columns: ['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'points', 'contestedShots', 'contestedShots2pt', 'contestedShots3pt', 'deflections', 'chargesDrawn', 'screenAssists', 'screenAssistPoints', 'looseBallsRecoveredOffensive', 'looseBallsRecoveredDefensive', 'looseBallsRecoveredTotal', 'offensiveBoxOuts', 'defensiveBoxOuts', 'boxOutPlayerTeamRebounds', 'boxOutPlayerRebounds', 'boxOuts']
                   
--- Table: player_info ---
Columns: ['PERSON_ID', 'FIRST_NAME', 'LAST_NAME', 'DISPLAY_FIRST_LAST', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FI_LAST', 'PLAYER_SLUG', 'BIRTHDATE', 'SCHOOL', 'COUNTRY', 'LAST_AFFILIATION', 'HEIGHT', 'WEIGHT', 'SEASON_EXP', 'JERSEY', 'POSITION', 'ROSTERSTATUS', 'GAMES_PLAYED_CURRENT_SEASON_FLAG', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE', 'TEAM_CITY', 'PLAYERCODE', 'FROM_YEAR', 'TO_YEAR', 'DLEAGUE_FLAG', 'NBA_FLAG', 'GAMES_PLAYED_FLAG', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'GREATEST_75_FLAG']


--- Table: nba_odds ---
Columns: ['GAME_DATE', 'status', 'home_team', 'home_team_loc', 'home_team_abbr', 'home_team_rank', 'away_team', 'away_team_loc', 'away_team_abbr', 'away_team_rank', 'home_score', 'away_score', 'home_spread_betmgm', 'home_spread_fanduel', 'home_spread_caesars', 'home_spread_bet365', 'home_spread_draftkings', 'home_spread_bet_rivers_ny', 'home_spread_odds_betmgm', 'home_spread_odds_fanduel', 'home_spread_odds_caesars', 'home_spread_odds_bet365', 'home_spread_odds_draftkings', 'home_spread_odds_bet_rivers_ny', 'away_spread_betmgm', 'away_spread_fanduel', 'away_spread_caesars', 'away_spread_bet365', 'away_spread_draftkings', 'away_spread_bet_rivers_ny', 'away_spread_odds_betmgm', 'away_spread_odds_fanduel', 'away_spread_odds_caesars', 'away_spread_odds_bet365', 'away_spread_odds_draftkings', 'away_spread_odds_bet_rivers_ny', 'home_ml_betmgm', 'home_ml_fanduel', 'home_ml_caesars', 'home_ml_bet365', 'home_ml_draftkings', 'home_ml_bet_rivers_ny', 'away_ml_betmgm', 'away_ml_fanduel', 'away_ml_caesars', 'away_ml_bet365', 'away_ml_draftkings', 'away_ml_bet_rivers_ny', 'total_betmgm', 'total_fanduel', 'total_caesars', 'total_bet365', 'total_draftkings', 'total_bet_rivers_ny', 'over_odds_betmgm', 'over_odds_fanduel', 'over_odds_caesars', 'over_odds_bet365', 'over_odds_draftkings', 'over_odds_bet_rivers_ny', 'under_odds_betmgm', 'under_odds_fanduel', 'under_odds_caesars', 'under_odds_bet365', 'under_odds_draftkings', 'under_odds_bet_rivers_ny', 'SEASON', 'derived_game_id']

In [12]:
from nba_api.stats.endpoints import commonallplayers, commonplayerinfo

player_info = commonplayerinfo.CommonPlayerInfo(player_id=2544).get_data_frames()  
player_info[0]

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GREATEST_75_FLAG
0,2544,LeBron,James,LeBron James,"James, LeBron",L. James,lebron-james,1984-12-30T00:00:00,St. Vincent-St. Mary HS (OH),USA,...,lebron_james,2003,2025,N,Y,Y,2003,1,1,Y

In [26]:
import sqlite3
import pandas as pd
import time
conn = sqlite3.connect('../data/nba_stats.db')


player_info = pd.read_sql("SELECT * FROM player_info", conn)
player_boxscores_basic = pd.read_sql("SELECT * FROM player_basic_stats", conn)

player_ids_in_db = set(player_info['PERSON_ID'].tolist())

player_ids_in_boxscores = set(player_boxscores_basic['personId'].tolist())

ids_to_load = player_ids_in_boxscores - player_ids_in_db

for p_id in ids_to_load:
    info = commonplayerinfo.CommonPlayerInfo(p_id).get_data_frames()[0]
    info = info.rename(columns = {'TEAM_ID':'teamId',
                                 'TEAM_NAME':'teamName',
                                 'TEAM_ABBREVIATION':'teamTricode'})
                                 
    info.to_sql("player_info", conn, if_exists='append', index=False)
    time.sleep(2)

In [28]:
player_boxscores_basic['seasonYear'].min()

'2013-14'

In [31]:
pd.read_sql("SELECT distinct teamTricode, teamId FROM team_basic_stats", conn).sort_values(['teamTricode'])

   teamTricode      teamId
28         ATL  1610612737
9          BKN  1610612751
16         BOS  1610612738
15         CHA  1610612766
4          CHI  1610612741
6          CLE  1610612739
18         DAL  1610612742
7          DEN  1610612743
27         DET  1610612765
19         GSW  1610612744
20         HOU  1610612745
3          IND  1610612754
5          LAC  1610612746
0          LAL  1610612747
29         MEM  1610612763
1          MIA  1610612748
21         MIL  1610612749
8          MIN  1610612750
17         NOP  1610612740
10         NYK  1610612752
11         OKC  1610612760
2          ORL  1610612753
22         PHI  1610612755
23         PHX  1610612756
24         POR  1610612757
25         SAC  1610612758
26         SAS  1610612759
12         TOR  1610612761
13         UTA  1610612762
14         WAS  1610612764

In [63]:
conn = sqlite3.connect("../data/nba_stats.db")
pd.read_sql("select * from sqlite_master where type='table'", conn)['name'].to_list()

['player_defensive_stats',
 'team_defensive_stats',
 'player_hustle_stats',
 'team_hustle_stats',
 'player_miscellaneous_stats',
 'team_miscellaneous_stats',
 'team_basic_stats',
 'player_basic_stats',
 'player_info',
 'team_basic_stats_by_position',
 'team_advanced_stats_by_position',
 'team_scoring_stats_by_position',
 'player_shot_locations_boxscores',
 'team_base_stats_by_position',
 'defensive_stats_by_position_backup',
 'defensive_stats_by_position',
 'team_shot_location_boxscores',
 'predictions_2024_25',
 'predictions_all_models_2024_25',
 'nba_odds',
 'predictions_multitask_model_2024_25',
 'predictions_multitask_model_2024_25_new',
 'team_aggregated_stats',
 'team_advanced_stats',
 'player_advanced_stats_v3',
 'team_advanced_stats_v3',
 'player_scoring_stats_v3',
 'team_scoring_stats_v3',
 'player_track_stats_v3',
 'team_track_stats_v3',
 'player_miscellaneous_stats_v3',
 'team_miscellaneous_stats_v3',
 'player_usage_stats_v3',
 'team_usage_stats_v3',
 'player_shot_location_boxscores',
 'team_game_full',
 'nba_odds_opening',
 'nba_arenas',
 'nba_injury_logs',
 'sqlite_sequence']

In [ ]:
tables = ['team_basic_stats_by_position',
 'team_advanced_stats_by_position',
 'team_scoring_stats_by_position',
 'team_base_stats_by_position',
 'defensive_stats_by_position_backup',
 'defensive_stats_by_position']

for table in tables:
    df = pd.read_sql(f"SELECT * FROM {table}", conn)
    print(f"Table: {table}")
    print(f"Shape: {df.shape}")
    display(df.head())

Table: team_basic_stats_by_position
Shape: (23048, 77)

,TEAM_ID,TEAM_NAME,Date,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,FGM_C,FGM_F,FGM_G,FGA_C,FGA_F,FGA_G,FG_PCT_C,FG_PCT_F,FG_PCT_G,FG3M_C,FG3M_F,FG3M_G,FG3A_C,FG3A_F,FG3A_G,FG3_PCT_C,FG3_PCT_F,FG3_PCT_G,FTM_C,FTM_F,FTM_G,FTA_C,FTA_F,FTA_G,FT_PCT_C,FT_PCT_F,FT_PCT_G,OREB_C,OREB_F,OREB_G,DREB_C,DREB_F,DREB_G,REB_C,REB_F,REB_G,AST_C,AST_F,AST_G,TOV_C,TOV_F,TOV_G,STL_C,STL_F,STL_G,BLK_C,BLK_F,BLK_G,BLKA_C,BLKA_F,BLKA_G,PF_C,PF_F,PF_G,PFD_C,PFD_F,PFD_G,PTS_C,PTS_F,PTS_G,PLUS_MINUS_C,PLUS_MINUS_F,PLUS_MINUS_G,SEASON,GAME_DATE
0,1610612737,Atlanta Hawks,2015-10-27,1.0,1,1,0.0,0.0,0.0,10.9,30.8,25.0,8.0,19.0,19.0,17.0,43.0,43.0,0.471,0.442,0.442,1.0,4.0,5.0,3.0,14.0,15.0,0.333,0.286,0.333,2.0,7.0,7.0,3.0,9.0,8.0,0.667,0.778,0.875,4.0,6.0,1.0,5.0,27.0,14.0,9.0,33.0,15.0,4.0,13.0,12.0,3.6,9.8,8.0,2.0,6.0,3.0,4.0,4.0,0.0,1.0,2.0,1.0,7.0,19.0,13.0,4.0,11.0,6.0,19.0,49.0,50.0,-0.6,-6.4,-7.0,2015-16,2015-10-27
1,1610612739,Cleveland Cavaliers,2015-10-27,1.0,1,1,0.0,0.0,0.0,9.2,31.7,19.0,3.0,26.0,13.0,10.0,63.0,37.0,0.300,0.413,0.351,0.0,6.0,3.0,0.0,20.0,13.0,0.000,0.300,0.231,1.0,7.0,4.0,2.0,12.0,7.0,0.500,0.583,0.571,4.0,8.0,2.0,13.0,29.0,11.0,17.0,37.0,13.0,2.0,13.0,14.0,2.2,7.2,4.2,1.0,4.0,2.0,2.0,4.0,2.0,2.0,7.0,2.0,6.0,16.0,8.0,4.0,15.0,8.0,7.0,65.0,33.0,-1.4,-1.4,-1.8,2015-16,2015-10-27
2,1610612740,New Orleans Pelicans,2015-10-27,1.0,1,1,0.0,0.0,0.0,13.5,23.3,18.1,12.0,15.0,12.0,32.0,40.0,31.0,0.375,0.375,0.387,0.0,3.0,3.0,2.0,8.0,10.0,0.000,0.375,0.300,10.0,15.0,4.0,15.0,21.0,6.0,0.667,0.714,0.667,4.0,4.0,1.0,10.0,15.0,5.0,14.0,19.0,6.0,3.0,4.0,16.0,5.6,8.8,7.2,0.0,4.0,5.0,3.0,3.0,0.0,1.0,2.0,5.0,8.0,11.0,11.0,11.0,16.0,11.0,34.0,48.0,31.0,-4.8,-9.4,-5.0,2015-16,2015-10-27
3,1610612741,Chicago Bulls,2015-10-27,0.0,0,0,1.0,1.0,1.0,9.7,32.1,19.8,1.0,21.0,22.0,7.0,48.0,53.0,0.143,0.438,0.415,0.0,6.0,1.0,1.0,14.0,7.0,0.000,0.429,0.143,0.0,14.0,7.0,2.0,17.0,9.0,0.000,0.824,0.778,2.0,5.0,1.0,9.0,27.0,10.0,11.0,32.0,11.0,4.0,3.0,8.0,2.6,8.2,5.4,2.0,4.0,3.0,6.0,10.0,1.0,0.0,2.0,5.0,2.0,17.0,5.0,7.0,13.0,6.0,2.0,62.0,52.0,-1.4,0.6,1.8,2015-16,2015-10-27
4,1610612744,Golden State Warriors,2015-10-27,0.0,0,0,1.0,1.0,1.0,9.3,20.1,25.8,14.0,9.0,21.0,23.0,34.0,49.0,0.609,0.265,0.429,1.0,4.0,5.0,1.0,12.0,19.0,1.000,0.333,0.263,5.0,9.0,10.0,6.0,10.0,10.0,0.833,0.900,1.000,8.0,13.0,5.0,6.0,14.0,20.0,14.0,27.0,25.0,7.0,9.0,17.0,4.2,8.2,12.0,1.0,4.0,4.0,4.0,1.0,3.0,2.0,0.0,1.0,5.0,15.0,12.0,7.0,14.0,8.0,34.0,31.0,57.0,2.4,9.0,5.8,2015-16,2015-10-27

Table: team_advanced_stats_by_position
Shape: (25670, 74)

,TEAM_ID,TEAM_NAME,Date,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,E_OFF_RATING_C,E_OFF_RATING_F,E_OFF_RATING_G,OFF_RATING_C,OFF_RATING_F,OFF_RATING_G,E_DEF_RATING_C,E_DEF_RATING_F,E_DEF_RATING_G,DEF_RATING_C,DEF_RATING_F,DEF_RATING_G,E_NET_RATING_C,E_NET_RATING_F,E_NET_RATING_G,NET_RATING_C,NET_RATING_F,NET_RATING_G,AST_PCT_C,AST_PCT_F,AST_PCT_G,AST_TO_C,AST_TO_F,AST_TO_G,AST_RATIO_C,AST_RATIO_F,AST_RATIO_G,OREB_PCT_C,OREB_PCT_F,OREB_PCT_G,DREB_PCT_C,DREB_PCT_F,DREB_PCT_G,REB_PCT_C,REB_PCT_F,REB_PCT_G,TM_TOV_PCT_C,TM_TOV_PCT_F,TM_TOV_PCT_G,EFG_PCT_C,EFG_PCT_F,EFG_PCT_G,TS_PCT_C,TS_PCT_F,TS_PCT_G,E_PACE_C,E_PACE_F,E_PACE_G,PACE_C,PACE_F,PACE_G,PACE_PER40_C,PACE_PER40_F,PACE_PER40_G,POSS_C,POSS_F,POSS_G,PIE_C,PIE_F,PIE_G,SEASON,GAME_DATE
0,1610612737,Atlanta Hawks,2015-10-27,1.0,1,1,0.0,0.0,0.0,11.0,31.0,25.0,101.4,100.1,94.6,20.9,22.7,27.1,100.4,106.1,106.5,20.7,24.2,30.2,1.0,-6.0,-11.9,0.2,-1.5,-3.1,0.523,0.598,0.591,1.28,1.49,1.38,3.4,4.3,6.0,0.143,0.171,0.125,0.600,0.567,0.560,0.404,0.397,0.378,0.034,0.036,0.045,0.533,0.513,0.488,0.519,0.522,0.537,99.1,98.2,98.6,479.85,431.50,346.38,399.88,359.58,288.65,107.0,272,178,0.512,0.472,0.453,2015-16,2015-10-27
1,1610612739,Cleveland Cavaliers,2015-10-27,1.0,1,1,0.0,0.0,0.0,9.0,32.0,19.0,89.1,94.6,91.6,18.1,28.8,22.0,93.8,95.3,94.1,19.6,29.3,23.1,-4.6,-0.7,-2.5,-1.5,-0.5,-1.1,0.667,0.675,0.689,2.18,2.36,2.43,1.8,4.8,6.9,0.268,0.271,0.276,0.769,0.761,0.748,0.509,0.505,0.502,0.023,0.033,0.025,0.439,0.454,0.441,0.322,0.476,0.412,103.6,102.2,102.8,502.87,333.74,422.78,419.06,278.12,352.32,96.0,220,167,0.502,0.511,0.506,2015-16,2015-10-27
2,1610612740,New Orleans Pelicans,2015-10-27,1.0,1,1,0.0,0.0,0.0,13.0,23.0,18.0,93.0,85.6,93.5,19.0,25.2,36.3,109.7,105.5,106.6,21.9,30.1,40.8,-16.7,-19.9,-13.2,-2.9,-4.9,-4.5,0.596,0.600,0.588,1.11,1.09,1.11,1.8,1.9,13.1,0.239,0.267,0.244,0.570,0.551,0.557,0.418,0.410,0.413,0.039,0.049,0.071,0.491,0.420,0.484,0.440,0.487,0.461,105.5,106.7,104.6,522.18,368.35,271.67,435.15,306.96,226.39,145.0,178,102,0.372,0.340,0.403,2015-16,2015-10-27
3,1610612741,Chicago Bulls,2015-10-27,0.0,0,0,1.0,1.0,1.0,10.0,32.0,20.0,92.2,96.1,93.3,19.2,27.9,22.9,101.6,97.0,90.4,20.4,27.6,21.8,-9.4,-0.9,3.0,-1.2,0.3,1.0,0.351,0.336,0.342,1.00,1.05,0.96,3.5,1.1,4.0,0.222,0.235,0.257,0.754,0.704,0.715,0.495,0.474,0.496,0.026,0.034,0.031,0.466,0.478,0.456,0.127,0.559,0.456,101.3,102.6,102.7,495.62,357.35,421.82,413.01,297.79,351.52,100.0,239,174,0.437,0.460,0.498,2015-16,2015-10-27
4,1610612744,Golden State Warriors,2015-10-27,0.0,0,0,1.0,1.0,1.0,9.0,20.0,26.0,100.2,111.3,100.8,20.2,28.1,35.7,88.4,90.4,89.5,17.5,23.0,32.3,11.8,20.9,11.3,2.7,5.1,3.4,0.711,0.700,0.709,1.29,1.54,1.22,5.7,3.9,8.0,0.392,0.483,0.465,0.750,0.716,0.730,0.573,0.595,0.591,0.042,0.047,0.075,0.477,0.485,0.444,0.663,0.404,0.534,105.3,106.0,105.5,527.40,418.31,295.04,439.50,348.59,245.86,101.0,175,159,0.604,0.648,0.589,2015-16,2015-10-27

Table: team_scoring_stats_by_position
Shape: (25670, 59)

,TEAM_ID,TEAM_NAME,Date,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,PCT_FGA_2PT_C,PCT_FGA_2PT_F,PCT_FGA_2PT_G,PCT_FGA_3PT_C,PCT_FGA_3PT_F,PCT_FGA_3PT_G,PCT_PTS_2PT_C,PCT_PTS_2PT_F,PCT_PTS_2PT_G,PCT_PTS_2PT_MR_C,PCT_PTS_2PT_MR_F,PCT_PTS_2PT_MR_G,PCT_PTS_3PT_C,PCT_PTS_3PT_F,PCT_PTS_3PT_G,PCT_PTS_FB_C,PCT_PTS_FB_F,PCT_PTS_FB_G,PCT_PTS_FT_C,PCT_PTS_FT_F,PCT_PTS_FT_G,PCT_PTS_OFF_TOV_C,PCT_PTS_OFF_TOV_F,PCT_PTS_OFF_TOV_G,PCT_PTS_PAINT_C,PCT_PTS_PAINT_F,PCT_PTS_PAINT_G,PCT_AST_2PM_C,PCT_AST_2PM_F,PCT_AST_2PM_G,PCT_UAST_2PM_C,PCT_UAST_2PM_F,PCT_UAST_2PM_G,PCT_AST_3PM_C,PCT_AST_3PM_F,PCT_AST_3PM_G,PCT_UAST_3PM_C,PCT_UAST_3PM_F,PCT_UAST_3PM_G,PCT_AST_FGM_C,PCT_AST_FGM_F,PCT_AST_FGM_G,PCT_UAST_FGM_C,PCT_UAST_FGM_F,PCT_UAST_FGM_G,SEASON,GAME_DATE
0,1610612737,Atlanta Hawks,2015-10-27,1.0,1,1,0.0,0.0,0.0,10.9,30.8,25.0,0.824,0.674,0.651,0.176,0.326,0.349,0.737,0.612,0.560,0.211,0.163,0.160,0.158,0.245,0.300,0.158,0.102,0.200,0.105,0.143,0.140,0.158,0.224,0.220,0.526,0.449,0.400,0.429,0.533,0.429,0.571,0.467,0.571,1.0,1.000,1.000,0.0,0.000,0.000,0.500,0.632,0.579,0.500,0.368,0.421,2015-16,2015-10-27
1,1610612739,Cleveland Cavaliers,2015-10-27,1.0,1,1,0.0,0.0,0.0,9.2,31.7,19.0,1.000,0.683,0.649,0.000,0.317,0.351,0.857,0.615,0.606,0.000,0.092,0.303,0.000,0.277,0.273,0.000,0.123,0.152,0.143,0.108,0.121,0.000,0.123,0.273,0.857,0.523,0.303,0.667,0.600,0.600,0.333,0.400,0.400,0.0,0.833,1.000,0.0,0.167,0.000,0.667,0.654,0.692,0.333,0.346,0.308,2015-16,2015-10-27
2,1610612740,New Orleans Pelicans,2015-10-27,1.0,1,1,0.0,0.0,0.0,13.5,23.3,18.1,0.938,0.800,0.677,0.063,0.200,0.323,0.706,0.500,0.581,0.235,0.208,0.194,0.000,0.188,0.290,0.118,0.333,0.065,0.294,0.313,0.129,0.176,0.458,0.226,0.471,0.292,0.387,0.833,0.833,0.000,0.167,0.167,1.000,0.0,1.000,0.333,0.0,0.000,0.667,0.833,0.867,0.083,0.167,0.133,0.917,2015-16,2015-10-27
3,1610612741,Chicago Bulls,2015-10-27,0.0,0,0,1.0,1.0,1.0,9.7,32.1,19.8,0.857,0.708,0.868,0.143,0.292,0.132,1.000,0.484,0.808,1.000,0.258,0.346,0.000,0.290,0.058,0.000,0.145,0.154,0.000,0.226,0.135,0.000,0.145,0.115,0.000,0.226,0.462,1.000,0.400,0.143,0.000,0.600,0.857,0.0,0.833,1.000,0.0,0.167,0.000,1.000,0.524,0.182,0.000,0.476,0.818,2015-16,2015-10-27
4,1610612744,Golden State Warriors,2015-10-27,0.0,0,0,1.0,1.0,1.0,9.3,20.1,25.8,0.957,0.647,0.612,0.043,0.353,0.388,0.765,0.323,0.561,0.000,0.129,0.105,0.088,0.387,0.263,0.000,0.065,0.228,0.147,0.290,0.175,0.059,0.452,0.246,0.765,0.194,0.456,0.923,1.000,0.438,0.077,0.000,0.563,1.0,1.000,0.600,0.0,0.000,0.400,0.929,1.000,0.476,0.071,0.000,0.524,2015-16,2015-10-27

Table: player_shot_locations_boxscores
Shape: (272147, 32)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,NICKNAME,Restricted Area FGM,Restricted Area FGA,Restricted Area FG_PCT,In The Paint (Non-RA) FGM,In The Paint (Non-RA) FGA,In The Paint (Non-RA) FG_PCT,Mid-Range FGM,Mid-Range FGA,Mid-Range FG_PCT,Left Corner 3 FGM,Left Corner 3 FGA,Left Corner 3 FG_PCT,Right Corner 3 FGM,Right Corner 3 FGA,Right Corner 3 FG_PCT,Above the Break 3 FGM,Above the Break 3 FGA,Above the Break 3 FG_PCT,Backcourt FGM,Backcourt FGA,Backcourt FG_PCT,Corner 3 FGM,Corner 3 FGA,Corner 3 FG_PCT,SEASON,Date
0,201166,Aaron Brooks,1610612741,CHI,31.0,Aaron,0.0,0.0,0.000,1.0,2.0,0.500,2.0,6.0,0.333,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,1.0,0.0,2015-16,2015-10-27
1,201143,Al Horford,1610612737,ATL,30.0,Al,2.0,2.0,1.000,1.0,1.0,1.000,2.0,5.0,0.400,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.333,0.0,0.0,0.0,0.0,0.0,0.0,2015-16,2015-10-27
2,201582,Alexis Ajinca,1610612740,NOP,28.0,Alexis,1.0,3.0,0.333,1.0,3.0,0.333,1.0,1.0,1.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2015-16,2015-10-27
3,202087,Alonzo Gee,1610612740,NOP,29.0,Alonzo,4.0,4.0,1.000,0.0,0.0,0.000,0.0,1.0,0.000,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2015-16,2015-10-27
4,2760,Anderson Varejao,1610612744,GSW,33.0,Anderson,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2015-16,2015-10-27

Table: team_base_stats_by_position
Shape: (2622, 77)

,TEAM_ID,TEAM_NAME,Date,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,FGM_C,FGM_F,FGM_G,FGA_C,FGA_F,FGA_G,FG_PCT_C,FG_PCT_F,FG_PCT_G,FG3M_C,FG3M_F,FG3M_G,FG3A_C,FG3A_F,FG3A_G,FG3_PCT_C,FG3_PCT_F,FG3_PCT_G,FTM_C,FTM_F,FTM_G,FTA_C,FTA_F,FTA_G,FT_PCT_C,FT_PCT_F,FT_PCT_G,OREB_C,OREB_F,OREB_G,DREB_C,DREB_F,DREB_G,REB_C,REB_F,REB_G,AST_C,AST_F,AST_G,TOV_C,TOV_F,TOV_G,STL_C,STL_F,STL_G,BLK_C,BLK_F,BLK_G,BLKA_C,BLKA_F,BLKA_G,PF_C,PF_F,PF_G,PFD_C,PFD_F,PFD_G,PTS_C,PTS_F,PTS_G,PLUS_MINUS_C,PLUS_MINUS_F,PLUS_MINUS_G,SEASON,GAME_DATE
0,1610612740,New Orleans Pelicans,2014-10-28,0.0,0,0,1.0,1.0,1.0,15.0,21.1,26.2,18.0,24.0,14.0,34.0,59.0,45.0,0.529,0.407,0.311,0.0,3.0,1.0,0.0,7.0,11.0,0.0,0.429,0.091,6.0,9.0,8.0,12.0,17.0,16.0,0.50,0.529,0.500,16.0,19.0,2.0,19.0,18.0,14.0,35.0,37.0,16.0,4.0,9.0,15.0,3.2,3.6,5.0,3.0,3.0,7.0,14.0,9.0,3.0,4.0,4.0,4.0,5.0,6.0,7.0,9.0,15.0,12.0,42.0,60.0,37.0,3.6,10.2,9.0,2014-15,2014-10-28
1,1610612742,Dallas Mavericks,2014-10-28,1.0,1,1,0.0,0.0,0.0,6.0,22.7,19.4,4.0,14.0,20.0,8.0,30.0,40.0,0.500,0.467,0.500,0.0,2.0,6.0,0.0,9.0,12.0,0.0,0.222,0.500,0.0,10.0,6.0,0.0,11.0,8.0,0.00,0.909,0.750,3.0,5.0,1.0,7.0,14.0,3.0,10.0,19.0,4.0,0.0,3.0,14.0,1.2,5.0,3.8,2.0,3.0,4.0,0.0,2.0,1.0,1.0,2.0,0.0,6.0,12.0,2.0,2.0,11.0,7.0,8.0,40.0,52.0,-1.4,-0.6,1.0,2014-15,2014-10-28
2,1610612745,Houston Rockets,2014-10-28,0.0,0,0,1.0,1.0,1.0,12.2,24.1,19.8,4.0,16.0,12.0,7.0,34.0,34.0,0.571,0.471,0.353,0.0,5.0,7.0,0.0,11.0,18.0,0.0,0.455,0.389,11.0,5.0,22.0,22.0,8.0,26.0,0.50,0.625,0.846,5.0,10.0,1.0,13.0,19.0,6.0,18.0,29.0,7.0,1.0,9.0,12.0,4.0,7.4,5.6,0.0,6.0,1.0,1.0,2.0,0.0,0.0,1.0,2.0,12.0,19.0,6.0,14.0,7.0,15.0,19.0,42.0,53.0,2.8,5.8,8.2,2014-15,2014-10-28
3,1610612747,Los Angeles Lakers,2014-10-28,1.0,1,1,0.0,0.0,0.0,6.1,20.8,24.8,3.0,16.0,9.0,12.0,34.0,37.0,0.250,0.471,0.243,0.0,1.0,2.0,0.0,3.0,7.0,0.0,0.333,0.286,3.0,7.0,24.0,4.0,11.0,28.0,0.75,0.636,0.857,4.0,6.0,2.0,6.0,10.0,9.0,10.0,16.0,11.0,1.0,2.0,13.0,1.4,5.8,6.6,1.0,3.0,4.0,1.0,2.0,0.0,0.0,0.0,3.0,4.0,14.0,15.0,5.0,8.0,20.0,9.0,40.0,44.0,0.4,-9.8,-9.8,2014-15,2014-10-28
4,1610612753,Orlando Magic,2014-10-28,1.0,1,1,0.0,0.0,0.0,12.9,17.9,21.5,10.0,18.0,6.0,25.0,36.0,31.0,0.400,0.500,0.194,0.0,2.0,2.0,1.0,5.0,6.0,0.0,0.400,0.333,2.0,6.0,8.0,4.0,8.0,9.0,0.50,0.750,0.889,7.0,4.0,5.0,21.0,10.0,11.0,28.0,14.0,16.0,6.0,5.0,11.0,4.8,6.2,8.4,2.0,3.0,1.0,8.0,4.0,0.0,4.0,6.0,9.0,7.0,10.0,12.0,4.0,7.0,7.0,22.0,44.0,22.0,-3.8,-6.6,-9.6,2014-15,2014-10-28

Table: defensive_stats_by_position_backup
Shape: (25700, 78)

,index,TEAM_ID,TEAM_NAME,Date,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,OPP_FGM_C,OPP_FGM_F,OPP_FGM_G,OPP_FGA_C,OPP_FGA_F,OPP_FGA_G,OPP_FG_PCT_C,OPP_FG_PCT_F,OPP_FG_PCT_G,OPP_FG3M_C,OPP_FG3M_F,OPP_FG3M_G,OPP_FG3A_C,OPP_FG3A_F,OPP_FG3A_G,OPP_FG3_PCT_C,OPP_FG3_PCT_F,OPP_FG3_PCT_G,OPP_FTM_C,OPP_FTM_F,OPP_FTM_G,OPP_FTA_C,OPP_FTA_F,OPP_FTA_G,OPP_FT_PCT_C,OPP_FT_PCT_F,OPP_FT_PCT_G,OPP_OREB_C,OPP_OREB_F,OPP_OREB_G,OPP_DREB_C,OPP_DREB_F,OPP_DREB_G,OPP_REB_C,OPP_REB_F,OPP_REB_G,OPP_AST_C,OPP_AST_F,OPP_AST_G,OPP_TOV_C,OPP_TOV_F,OPP_TOV_G,OPP_STL_C,OPP_STL_F,OPP_STL_G,OPP_BLK_C,OPP_BLK_F,OPP_BLK_G,OPP_BLKA_C,OPP_BLKA_F,OPP_BLKA_G,OPP_PF_C,OPP_PF_F,OPP_PF_G,OPP_PFD_C,OPP_PFD_F,OPP_PFD_G,OPP_PTS_C,OPP_PTS_F,OPP_PTS_G,PLUS_MINUS_C,PLUS_MINUS_F,PLUS_MINUS_G,SEASON,GAME_DATE
0,0,1610612739,Cleveland Cavaliers,2016-10-25,0.0,0,0,1.0,1.0,1.0,5.6,26.2,23.0,4.4,15.6,16.6,10.2,47.4,42.2,0.431,0.329,0.393,1.0,4.4,5.0,2.8,15.6,14.0,0.357,0.282,0.357,1.0,9.2,6.8,1.6,11.6,9.6,0.625,0.793,0.708,1.4,7.2,5.8,3.6,16.2,14.0,5.0,23.4,19.8,2.2,8.8,9.4,2.4,10.0,8.0,0.4,3.4,2.8,1.0,2.8,2.4,0.4,3.0,2.6,2.8,12.8,9.6,2.4,12.0,10.8,10.8,44.8,45.0,-3.6,-19.0,-10.6,2016-17,2016-10-25
1,1,1610612744,Golden State Warriors,2016-10-25,1.0,1,1,0.0,0.0,0.0,5.4,22.1,25.9,5.2,22.0,25.6,10.8,45.6,53.4,0.481,0.482,0.479,1.0,6.0,7.0,2.2,11.6,13.4,0.455,0.517,0.522,2.4,10.6,13.2,2.6,12.2,15.0,0.923,0.869,0.880,2.2,9.8,12.0,3.6,15.6,18.4,5.8,25.4,30.4,3.0,11.4,13.8,1.4,6.4,7.8,1.2,6.2,7.4,0.4,1.4,1.4,0.4,3.0,3.6,2.6,8.4,10.2,2.4,8.6,10.8,13.8,60.6,71.4,3.4,13.0,18.2,2016-17,2016-10-25
2,2,1610612752,New York Knicks,2016-10-25,1.0,1,1,0.0,0.0,0.0,8.9,20.8,21.4,8.0,19.6,20.2,18.6,41.4,40.8,0.430,0.473,0.495,2.0,5.4,6.0,6.2,15.0,15.4,0.323,0.360,0.390,2.2,5.8,7.2,3.0,7.8,9.8,0.733,0.744,0.735,2.8,4.8,4.4,6.2,17.0,19.0,9.0,21.8,23.4,5.6,13.2,13.8,1.8,6.4,7.2,2.4,5.6,5.0,1.4,1.8,2.2,1.0,3.0,2.4,4.6,8.8,9.8,3.0,9.4,11.0,20.2,50.4,53.6,2.8,13.0,15.2,2016-17,2016-10-25
3,3,1610612757,Portland Trail Blazers,2016-10-25,0.0,0,0,1.0,1.0,1.0,4.8,25.3,25.0,4.6,21.6,20.6,8.0,43.8,43.2,0.575,0.493,0.477,1.4,4.4,3.6,2.6,13.4,11.8,0.538,0.328,0.305,2.2,7.6,7.0,2.2,7.6,7.0,1.000,1.000,1.000,0.6,3.2,3.4,3.2,13.0,13.2,3.8,16.2,16.6,2.8,10.0,9.0,1.2,7.8,7.2,1.0,4.8,4.6,0.6,2.6,2.6,0.2,1.6,1.8,1.4,10.2,10.0,2.0,9.0,8.6,12.8,55.2,51.8,2.8,-5.0,-7.4,2016-17,2016-10-25
4,4,1610612759,San Antonio Spurs,2016-10-25,0.0,0,0,1.0,1.0,1.0,9.2,26.5,24.6,7.8,22.2,20.2,17.0,47.0,42.0,0.459,0.472,0.481,1.4,4.0,3.0,6.6,18.2,15.6,0.212,0.220,0.192,1.6,7.8,7.2,2.8,10.0,10.2,0.571,0.780,0.706,1.6,4.8,3.2,5.4,15.0,13.2,7.0,19.8,16.4,4.0,13.6,12.6,3.6,8.8,8.2,2.2,5.8,5.6,1.4,3.2,3.2,0.6,1.8,1.2,3.4,11.4,9.0,3.2,10.8,10.2,18.6,56.2,50.6,-5.8,-14.4,-17.2,2016-17,2016-10-25

Table: defensive_stats_by_position
Shape: (32064, 76)

,teamId,teamName,gameDate,L_C,L_F,L_G,W_PCT_C,W_PCT_F,W_PCT_G,MIN_C,MIN_F,MIN_G,OPP_FGM_C,OPP_FGM_F,OPP_FGM_G,OPP_FGA_C,OPP_FGA_F,OPP_FGA_G,OPP_FG_PCT_C,OPP_FG_PCT_F,OPP_FG_PCT_G,OPP_FG3M_C,OPP_FG3M_F,OPP_FG3M_G,OPP_FG3A_C,OPP_FG3A_F,OPP_FG3A_G,OPP_FG3_PCT_C,OPP_FG3_PCT_F,OPP_FG3_PCT_G,OPP_FTM_C,OPP_FTM_F,OPP_FTM_G,OPP_FTA_C,OPP_FTA_F,OPP_FTA_G,OPP_FT_PCT_C,OPP_FT_PCT_F,OPP_FT_PCT_G,OPP_OREB_C,OPP_OREB_F,OPP_OREB_G,OPP_DREB_C,OPP_DREB_F,OPP_DREB_G,OPP_REB_C,OPP_REB_F,OPP_REB_G,OPP_AST_C,OPP_AST_F,OPP_AST_G,OPP_TOV_C,OPP_TOV_F,OPP_TOV_G,OPP_STL_C,OPP_STL_F,OPP_STL_G,OPP_BLK_C,OPP_BLK_F,OPP_BLK_G,OPP_BLKA_C,OPP_BLKA_F,OPP_BLKA_G,OPP_PF_C,OPP_PF_F,OPP_PF_G,OPP_PFD_C,OPP_PFD_F,OPP_PFD_G,OPP_PTS_C,OPP_PTS_F,OPP_PTS_G,PLUS_MINUS_C,PLUS_MINUS_F,PLUS_MINUS_G,season
0,1610612739,Cleveland Cavaliers,2016-10-25,0.0,0.0,0.0,1.0,1.0,1.0,5.6,26.2,23.0,4.4,15.6,16.6,10.2,47.4,42.2,0.431,0.329,0.393,1.0,4.4,5.0,2.8,15.6,14.0,0.357,0.282,0.357,1.0,9.2,6.8,1.6,11.6,9.6,0.625,0.793,0.708,1.4,7.2,5.8,3.6,16.2,14.0,5.0,23.4,19.8,2.2,8.8,9.4,2.4,10.0,8.0,0.4,3.4,2.8,1.0,2.8,2.4,0.4,3.0,2.6,2.8,12.8,9.6,2.4,12.0,10.8,10.8,44.8,45.0,-3.6,-19.0,-10.6,2016-17
1,1610612744,Golden State Warriors,2016-10-25,1.0,1.0,1.0,0.0,0.0,0.0,5.4,22.1,25.9,5.2,22.0,25.6,10.8,45.6,53.4,0.481,0.482,0.479,1.0,6.0,7.0,2.2,11.6,13.4,0.455,0.517,0.522,2.4,10.6,13.2,2.6,12.2,15.0,0.923,0.869,0.880,2.2,9.8,12.0,3.6,15.6,18.4,5.8,25.4,30.4,3.0,11.4,13.8,1.4,6.4,7.8,1.2,6.2,7.4,0.4,1.4,1.4,0.4,3.0,3.6,2.6,8.4,10.2,2.4,8.6,10.8,13.8,60.6,71.4,3.4,13.0,18.2,2016-17
2,1610612752,New York Knicks,2016-10-25,1.0,1.0,1.0,0.0,0.0,0.0,8.9,20.8,21.4,8.0,19.6,20.2,18.6,41.4,40.8,0.430,0.473,0.495,2.0,5.4,6.0,6.2,15.0,15.4,0.323,0.360,0.390,2.2,5.8,7.2,3.0,7.8,9.8,0.733,0.744,0.735,2.8,4.8,4.4,6.2,17.0,19.0,9.0,21.8,23.4,5.6,13.2,13.8,1.8,6.4,7.2,2.4,5.6,5.0,1.4,1.8,2.2,1.0,3.0,2.4,4.6,8.8,9.8,3.0,9.4,11.0,20.2,50.4,53.6,2.8,13.0,15.2,2016-17
3,1610612757,Portland Trail Blazers,2016-10-25,0.0,0.0,0.0,1.0,1.0,1.0,4.8,25.3,25.0,4.6,21.6,20.6,8.0,43.8,43.2,0.575,0.493,0.477,1.4,4.4,3.6,2.6,13.4,11.8,0.538,0.328,0.305,2.2,7.6,7.0,2.2,7.6,7.0,1.000,1.000,1.000,0.6,3.2,3.4,3.2,13.0,13.2,3.8,16.2,16.6,2.8,10.0,9.0,1.2,7.8,7.2,1.0,4.8,4.6,0.6,2.6,2.6,0.2,1.6,1.8,1.4,10.2,10.0,2.0,9.0,8.6,12.8,55.2,51.8,2.8,-5.0,-7.4,2016-17
4,1610612759,San Antonio Spurs,2016-10-25,0.0,0.0,0.0,1.0,1.0,1.0,9.2,26.5,24.6,7.8,22.2,20.2,17.0,47.0,42.0,0.459,0.472,0.481,1.4,4.0,3.0,6.6,18.2,15.6,0.212,0.220,0.192,1.6,7.8,7.2,2.8,10.0,10.2,0.571,0.780,0.706,1.6,4.8,3.2,5.4,15.0,13.2,7.0,19.8,16.4,4.0,13.6,12.6,3.6,8.8,8.2,2.2,5.8,5.6,1.4,3.2,3.2,0.6,1.8,1.2,3.4,11.4,9.0,3.2,10.8,10.2,18.6,56.2,50.6,-5.8,-14.4,-17.2,2016-17

In [88]:

conn = sqlite3.connect("../data/nba_stats.db")
df = pd.read_sql("select * From team_game_full", conn)
df['gameId'].str[:3].value_counts()

gameId
002    29912
004     2008
005       62
Name: count, dtype: int64

In [76]:
tslb = pd.read_sql("select * From team_shot_location_boxscores", conn)

tslb.loc[(tslb.isnull().any(axis=1)) & (tslb['season'] == '2013-14')].isnull().sum()

teamId                            0
teamName                          0
Restricted Area FGM               0
Restricted Area FGA               0
Restricted Area FG_PCT            0
In The Paint (Non-RA) FGM         0
In The Paint (Non-RA) FGA         0
In The Paint (Non-RA) FG_PCT      0
Mid-Range FGM                     0
Mid-Range FGA                     0
Mid-Range FG_PCT                  0
Left Corner 3 FGM                20
Left Corner 3 FGA                20
Left Corner 3 FG_PCT             20
Right Corner 3 FGM               16
Right Corner 3 FGA               16
Right Corner 3 FG_PCT            16
Above the Break 3 FGM             0
Above the Break 3 FGA             0
Above the Break 3 FG_PCT          0
Backcourt FGM                   268
Backcourt FGA                   268
Backcourt FG_PCT                268
Corner 3 FGM                      0
Corner 3 FGA                      0
Corner 3 FG_PCT                   0
season                            0
gameDate                          0
dtype: int64

In [89]:
pd.set_option('display.max_rows', 100)

df.loc[df['Corner 3 FGA'].isnull()]

Empty DataFrame
Columns: [seasonYear, teamId, teamTricode, gameId, gameDate, MATCHUP, WL, minutes, points, plusMinus, fieldGoalsMade, fieldGoalsAttempted, fieldGoalPercentage, threePointersMade, threePointersAttempted, threePointerPercentage, freeThrowsMade, freeThrowsAttempted, freeThrowPercentage, offensiveRebounds, defensiveRebounds, rebounds, assists, steals, blocks, turnovers, personalFouls, offensiveRating, defensiveRating, netRating, assistPercentage, assistToTurnover, assistRatio, offensiveReboundPercentage, defensiveReboundPercentage, reboundPercentage, effectiveFieldGoalPercentage, trueShootingPercentage, usagePercentage, pace, PIE, percentageFieldGoalsAttempted2pt, percentageFieldGoalsAttempted3pt, percentagePoints2pt, percentagePointsMidrange2pt, percentagePoints3pt, percentagePointsFastBreak, percentagePointsFreeThrow, percentagePointsOffTurnovers, percentagePointsPaint, percentageAssisted2pt, percentageUnassisted2pt, percentageAssisted3pt, percentageUnassisted3pt, percentageAssistedFGM, percentageUnassistedFGM, distance, touches, secondaryAssists, freeThrowAssists, passes, contestedFieldGoalsMade, contestedFieldGoalsAttempted, contestedFieldGoalPercentage, uncontestedFieldGoalsMade, uncontestedFieldGoalsAttempted, uncontestedFieldGoalsPercentage, defendedAtRimFieldGoalsMade, defendedAtRimFieldGoalsAttempted, defendedAtRimFieldGoalPercentage, reboundChancesOffensive, reboundChancesDefensive, reboundChancesTotal, Restricted Area FGM, Restricted Area FGA, Restricted Area FG_PCT, In The Paint (Non-RA) FGM, In The Paint (Non-RA) FGA, In The Paint (Non-RA) FG_PCT, Mid-Range FGM, Mid-Range FGA, Mid-Range FG_PCT, Above the Break 3 FGM, Above the Break 3 FGA, Above the Break 3 FG_PCT, Corner 3 FGM, Corner 3 FGA, Corner 3 FG_PCT, OPP_FGM_C, OPP_FGM_F, OPP_FGM_G, OPP_FGA_C, OPP_FGA_F, OPP_FGA_G, OPP_FG_PCT_C, OPP_FG_PCT_F, OPP_FG_PCT_G, OPP_FG3M_C, OPP_FG3M_F, OPP_FG3M_G, ...]
Index: []

In [27]:
tbs.loc[tbs['gameId'] == '0021400445']

,SEASON_ID,teamId,teamTricode,teamName,gameId,gameDate,MATCHUP,WL,minutes,fieldGoalsMade,...,defensiveRebounds,rebounds,assists,steals,blocks,turnovers,personalFouls,points,plusMinus,seasonYear
3532,22014,1610612764,WAS,Washington Wizards,0021400445,2014-12-27,WAS vs. BOS,W,240,45,...,39,48,28,11,4,18,24,101,13,2014-15
3533,22014,1610612738,BOS,Boston Celtics,0021400445,2014-12-27,BOS @ WAS,L,240,32,...,28,36,17,10,2,18,15,88,-13,2014-15

In [35]:
pd.set_option('display.max_rows', 170)

hustle = pd.read_sql("""select * from team_hustle_stats""", conn)
tbs = pd.read_sql("""select * from team_basic_stats""", conn)
track = pd.read_sql("""select * From team_track_stats_v3""", conn)
tbs

,SEASON_ID,teamId,teamTricode,teamName,gameId,gameDate,MATCHUP,WL,minutes,fieldGoalsMade,...,defensiveRebounds,rebounds,assists,steals,blocks,turnovers,personalFouls,points,plusMinus,seasonYear
0,22013,1610612747,LAL,Los Angeles Lakers,0021300003,2013-10-29,LAL vs. LAC,W,240,42,...,34,52,23,8,6,19,23,116,13,2013-14
1,22013,1610612748,MIA,Miami Heat,0021300002,2013-10-29,MIA vs. CHI,W,240,37,...,35,40,26,10,7,20,21,107,12,2013-14
2,22013,1610612753,ORL,Orlando Magic,0021300001,2013-10-29,ORL @ IND,L,240,36,...,26,39,17,10,6,19,26,87,-10,2013-14
3,22013,1610612754,IND,Indiana Pacers,0021300001,2013-10-29,IND vs. ORL,W,240,34,...,34,44,17,4,18,21,13,97,10,2013-14
4,22013,1610612741,CHI,Chicago Bulls,0021300002,2013-10-29,CHI @ MIA,L,240,35,...,30,41,23,11,4,19,27,95,-12,2013-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31977,22025,1610612757,POR,Portland Trail Blazers,0022500490,2026-01-03,POR @ SAS,W,240,40,...,36,52,24,3,4,11,16,115,5,2025-26
31978,22025,1610612742,DAL,Dallas Mavericks,0022500491,2026-01-03,DAL vs. HOU,W,240,44,...,45,47,24,6,10,16,15,110,6,2025-26
31979,22025,1610612745,HOU,Houston Rockets,0022500491,2026-01-03,HOU @ DAL,L,240,41,...,34,51,24,13,7,9,17,104,-6,2025-26
31980,22025,1610612741,CHI,Chicago Bulls,0022500489,2026-01-03,CHI vs. CHA,L,240,39,...,37,43,32,9,5,11,16,99,-13,2025-26
31981,22025,1610612759,SAS,San Antonio Spurs,0022500490,2026-01-03,SAS vs. POR,L,240,40,...,36,48,27,8,7,6,20,110,-5,2025-26

In [67]:
set(tbs.loc[tbs['seasonYear'] >= '2015-16', 'gameId'].tolist()) - set(hustle['gameId'].tolist())

{'0021500120', '0021500236', '0021500437', '0021500675', '0021501131'}

In [71]:
track['gameId'].str[3:5].value_counts().sort_index()

gameId
13    2638
14    2622
15    2632
16    2618
17    2624
18    2624
19    2286
20    2332
21    2608
22    2604
23    2618
24    2604
25    1222
Name: count, dtype: int64

In [70]:
hustle['gameId'].str[3:5].value_counts().sort_index()

gameId
13     148
14      78
15    1527
16    2618
17    2624
18    2624
19    2286
20    2342
21    2646
22    2800
23    2636
24    2640
25    1218
Name: count, dtype: int64

In [90]:
pd.options.display.max_columns = 200
df.loc[df['Above the Break 3 FGM'].isnull()]

Empty DataFrame
Columns: [seasonYear, teamId, teamTricode, gameId, gameDate, MATCHUP, WL, minutes, points, plusMinus, fieldGoalsMade, fieldGoalsAttempted, fieldGoalPercentage, threePointersMade, threePointersAttempted, threePointerPercentage, freeThrowsMade, freeThrowsAttempted, freeThrowPercentage, offensiveRebounds, defensiveRebounds, rebounds, assists, steals, blocks, turnovers, personalFouls, offensiveRating, defensiveRating, netRating, assistPercentage, assistToTurnover, assistRatio, offensiveReboundPercentage, defensiveReboundPercentage, reboundPercentage, effectiveFieldGoalPercentage, trueShootingPercentage, usagePercentage, pace, PIE, percentageFieldGoalsAttempted2pt, percentageFieldGoalsAttempted3pt, percentagePoints2pt, percentagePointsMidrange2pt, percentagePoints3pt, percentagePointsFastBreak, percentagePointsFreeThrow, percentagePointsOffTurnovers, percentagePointsPaint, percentageAssisted2pt, percentageUnassisted2pt, percentageAssisted3pt, percentageUnassisted3pt, percentageAssistedFGM, percentageUnassistedFGM, distance, touches, secondaryAssists, freeThrowAssists, passes, contestedFieldGoalsMade, contestedFieldGoalsAttempted, contestedFieldGoalPercentage, uncontestedFieldGoalsMade, uncontestedFieldGoalsAttempted, uncontestedFieldGoalsPercentage, defendedAtRimFieldGoalsMade, defendedAtRimFieldGoalsAttempted, defendedAtRimFieldGoalPercentage, reboundChancesOffensive, reboundChancesDefensive, reboundChancesTotal, Restricted Area FGM, Restricted Area FGA, Restricted Area FG_PCT, In The Paint (Non-RA) FGM, In The Paint (Non-RA) FGA, In The Paint (Non-RA) FG_PCT, Mid-Range FGM, Mid-Range FGA, Mid-Range FG_PCT, Above the Break 3 FGM, Above the Break 3 FGA, Above the Break 3 FG_PCT, Corner 3 FGM, Corner 3 FGA, Corner 3 FG_PCT, OPP_FGM_C, OPP_FGM_F, OPP_FGM_G, OPP_FGA_C, OPP_FGA_F, OPP_FGA_G, OPP_FG_PCT_C, OPP_FG_PCT_F, OPP_FG_PCT_G, OPP_FG3M_C, OPP_FG3M_F, OPP_FG3M_G, ...]
Index: []

In [91]:
import pandas as pd
pd.set_option('display.max_rows', 200)
df = pd.read_sql("""select * from team_game_full""", conn)

df.isnull().sum().reset_index()

                                index  0
0                          seasonYear  0
1                              teamId  0
2                         teamTricode  0
3                              gameId  0
4                            gameDate  0
5                             MATCHUP  0
6                                  WL  0
7                             minutes  0
8                              points  0
9                           plusMinus  0
10                     fieldGoalsMade  0
11                fieldGoalsAttempted  0
12                fieldGoalPercentage  0
13                  threePointersMade  0
14             threePointersAttempted  0
15             threePointerPercentage  0
16                     freeThrowsMade  0
17                freeThrowsAttempted  0
18                freeThrowPercentage  0
19                  offensiveRebounds  0
20                  defensiveRebounds  0
21                           rebounds  0
22                            assists  0
23                             steals  0
24                             blocks  0
25                          turnovers  0
26                      personalFouls  0
27                    offensiveRating  0
28                    defensiveRating  0
29                          netRating  0
30                   assistPercentage  0
31                   assistToTurnover  0
32                        assistRatio  0
33         offensiveReboundPercentage  0
34         defensiveReboundPercentage  0
35                  reboundPercentage  0
36       effectiveFieldGoalPercentage  0
37             trueShootingPercentage  0
38                    usagePercentage  0
39                               pace  0
40                                PIE  0
41   percentageFieldGoalsAttempted2pt  0
42   percentageFieldGoalsAttempted3pt  0
43                percentagePoints2pt  0
44        percentagePointsMidrange2pt  0
45                percentagePoints3pt  0
46          percentagePointsFastBreak  0
47          percentagePointsFreeThrow  0
48       percentagePointsOffTurnovers  0
49              percentagePointsPaint  0
50              percentageAssisted2pt  0
51            percentageUnassisted2pt  0
52              percentageAssisted3pt  0
53            percentageUnassisted3pt  0
54              percentageAssistedFGM  0
55            percentageUnassistedFGM  0
56                           distance  0
57                            touches  0
58                   secondaryAssists  0
59                   freeThrowAssists  0
60                             passes  0
61            contestedFieldGoalsMade  0
62       contestedFieldGoalsAttempted  0
63       contestedFieldGoalPercentage  0
64          uncontestedFieldGoalsMade  0
65     uncontestedFieldGoalsAttempted  0
66    uncontestedFieldGoalsPercentage  0
67        defendedAtRimFieldGoalsMade  0
68   defendedAtRimFieldGoalsAttempted  0
69   defendedAtRimFieldGoalPercentage  0
70            reboundChancesOffensive  0
71            reboundChancesDefensive  0
72                reboundChancesTotal  0
73                Restricted Area FGM  0
74                Restricted Area FGA  0
75             Restricted Area FG_PCT  0
76          In The Paint (Non-RA) FGM  0
77          In The Paint (Non-RA) FGA  0
78       In The Paint (Non-RA) FG_PCT  0
79                      Mid-Range FGM  0
80                      Mid-Range FGA  0
81                   Mid-Range FG_PCT  0
82              Above the Break 3 FGM  0
83              Above the Break 3 FGA  0
84           Above the Break 3 FG_PCT  0
85                       Corner 3 FGM  0
86                       Corner 3 FGA  0
87                    Corner 3 FG_PCT  0
88                          OPP_FGM_C  0
89                          OPP_FGM_F  0
90                          OPP_FGM_G  0
91                          OPP_FGA_C  0
92                          OPP_FGA_F  0
93                          OPP_FGA_G  0
94                       OPP_FG_PCT_C  0
95                       OPP_FG_PCT_F  0
96                       OPP_FG_PCT_G  0
97                         OPP_FG3M_C  0
98                         OPP_FG3M_F  0
99                         OPP_FG3M_G  0
100                        OPP_FG3A_C  0
101                        OPP_FG3A_F  0
102                        OPP_FG3A_G  0
103                     OPP_FG3_PCT_C  0
104                     OPP_FG3_PCT_F  0
105                     OPP_FG3_PCT_G  0
106                         OPP_FTM_C  0
107                         OPP_FTM_F  0
108                         OPP_FTM_G  0
109                         OPP_FTA_C  0
110                         OPP_FTA_F  0
111                         OPP_FTA_G  0
112                      OPP_FT_PCT_C  0
113                      OPP_FT_PCT_F  0
114                      OPP_FT_PCT_G  0
115                        OPP_OREB_C  0
116                        OPP_OREB_F  0
117                        OPP_OREB_G  0
118                        OPP_DREB_C  0
119                        OPP_DREB_F  0
120                        OPP_DREB_G  0
121                         OPP_REB_C  0
122                         OPP_REB_F  0
123                         OPP_REB_G  0
124                         OPP_AST_C  0
125                         OPP_AST_F  0
126                         OPP_AST_G  0
127                         OPP_TOV_C  0
128                         OPP_TOV_F  0
129                         OPP_TOV_G  0
130                         OPP_STL_C  0
131                         OPP_STL_F  0
132                         OPP_STL_G  0
133                         OPP_BLK_C  0
134                         OPP_BLK_F  0
135                         OPP_BLK_G  0
136                        OPP_BLKA_C  0
137                        OPP_BLKA_F  0
138                        OPP_BLKA_G  0
139                          OPP_PF_C  0
140                          OPP_PF_F  0
141                          OPP_PF_G  0
142                         OPP_PFD_C  0
143                         OPP_PFD_F  0
144                         OPP_PFD_G  0
145                         OPP_PTS_C  0
146                         OPP_PTS_F  0
147                         OPP_PTS_G  0
148                  PLUS_MINUS_C_DEF  0
149                  PLUS_MINUS_F_DEF  0
150                  PLUS_MINUS_G_DEF  0

In [53]:
df.loc[df['contestedShots'].isnull()]

,seasonYear,teamId,teamTricode,gameId,gameDate,MATCHUP,WL,minutes,points,plusMinus,...,OPP_PF_G,OPP_PFD_C,OPP_PFD_F,OPP_PFD_G,OPP_PTS_C,OPP_PTS_F,OPP_PTS_G,PLUS_MINUS_C_DEF,PLUS_MINUS_F_DEF,PLUS_MINUS_G_DEF
0,2015-16,1610612739,CLE,0021500002,2015-10-27,CLE @ CHI,L,240,95,-2,...,8.8,3.8,14.6,8.8,18.8,64.8,38.6,1.4,1.4,1.8
2,2015-16,1610612741,CHI,0021500002,2015-10-27,CHI vs. CLE,W,240,97,2,...,8.6,3.8,15.4,9.4,20.6,66.0,38.0,1.4,-0.6,-1.8
4,2015-16,1610612765,DET,0021500001,2015-10-27,DET @ ATL,W,240,106,12,...,10.0,3.0,7.2,6.0,18.8,42.6,37.6,-2.4,-2.6,-4.8
5,2015-16,1610612737,ATL,0021500001,2015-10-27,ATL vs. DET,L,240,94,-12,...,8.6,6.0,16.2,13.4,23.0,68.2,55.2,0.6,6.4,7.0
6,2015-16,1610612738,BOS,0021500005,2015-10-28,BOS vs. PHI,W,240,112,17,...,11.4,5.6,13.8,11.0,23.4,56.6,44.4,1.0,-8.8,-12.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,2015-16,1610612761,TOR,0021501218,2016-04-13,TOR @ BKN,W,240,103,7,...,8.6,3.6,5.8,6.2,28.2,45.2,48.6,0.2,-3.0,-4.2
2456,2015-16,1610612766,CHA,0021501219,2016-04-13,CHA vs. ORL,W,240,117,14,...,10.8,4.2,4.0,8.4,32.4,22.4,61.8,-1.8,-4.4,-8.4
2457,2015-16,1610612740,NOP,0021501226,2016-04-13,NOP @ MIN,L,240,109,-35,...,9.8,3.2,7.6,7.6,32.2,66.2,69.2,9.0,17.6,17.2
2458,2015-16,1610612741,CHI,0021501222,2016-04-13,CHI vs. PHI,W,240,115,10,...,6.2,1.6,10.4,4.0,10.6,85.6,28.6,-4.0,-11.2,-1.6
2459,2015-16,1610612751,BKN,0021501218,2016-04-13,BKN vs. TOR,L,240,96,-7,...,10.0,1.0,7.2,14.6,8.6,43.8,86.2,0.4,2.4,6.4

In [51]:
df.loc[df['contestedShots'].isnull(), 'seasonYear'].value_counts()

df['seasonYear'].value_counts().sort_index()

seasonYear
2015-16    2632
2016-17    2618
2017-18    2624
2018-19    2624
2019-20    2286
2020-21    2342
2021-22    2646
2022-23    2640
2023-24    2636
2024-25    2640
2025-26    1034
Name: count, dtype: int64

In [ ]:
conn.close()

In [60]:
pd.options.display.max_columns = 100
display(pd.read_sql("select * from team_advanced_stat", conn))
display(pd.read_sql("select * from team_advanced_stats_v3", conn))

DatabaseError: Execution failed on sql 'select * from team_advanced_stat': no such table: team_advanced_stat

In [77]:
pd.set_option('display.max_rows', 100)

df.loc[df['Corner 3 FGA'].isnull()]

,seasonYear,teamId,teamTricode,gameId,gameDate,MATCHUP,WL,minutes,points,plusMinus,fieldGoalsMade,fieldGoalsAttempted,fieldGoalPercentage,threePointersMade,threePointersAttempted,threePointerPercentage,freeThrowsMade,freeThrowsAttempted,freeThrowPercentage,offensiveRebounds,defensiveRebounds,rebounds,assists,steals,blocks,turnovers,personalFouls,offensiveRating,defensiveRating,netRating,assistPercentage,assistToTurnover,assistRatio,offensiveReboundPercentage,defensiveReboundPercentage,reboundPercentage,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,pace,PIE,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,distance,touches,secondaryAssists,freeThrowAssists,passes,contestedFieldGoalsMade,contestedFieldGoalsAttempted,contestedFieldGoalPercentage,uncontestedFieldGoalsMade,uncontestedFieldGoalsAttempted,uncontestedFieldGoalsPercentage,defendedAtRimFieldGoalsMade,defendedAtRimFieldGoalsAttempted,defendedAtRimFieldGoalPercentage,reboundChancesOffensive,reboundChancesDefensive,reboundChancesTotal,Restricted Area FGM,Restricted Area FGA,Restricted Area FG_PCT,In The Paint (Non-RA) FGM,In The Paint (Non-RA) FGA,In The Paint (Non-RA) FG_PCT,Mid-Range FGM,Mid-Range FGA,Mid-Range FG_PCT,Above the Break 3 FGM,Above the Break 3 FGA,Above the Break 3 FG_PCT,Corner 3 FGM,Corner 3 FGA,Corner 3 FG_PCT,OPP_FGM_C,OPP_FGM_F,OPP_FGM_G,OPP_FGA_C,OPP_FGA_F,OPP_FGA_G,OPP_FG_PCT_C,OPP_FG_PCT_F,OPP_FG_PCT_G,OPP_FG3M_C,OPP_FG3M_F,OPP_FG3M_G,OPP_FG3A_C,OPP_FG3A_F,OPP_FG3A_G,OPP_FG3_PCT_C,OPP_FG3_PCT_F,OPP_FG3_PCT_G,OPP_FTM_C,OPP_FTM_F,OPP_FTM_G,OPP_FTA_C,OPP_FTA_F,OPP_FTA_G,OPP_FT_PCT_C,OPP_FT_PCT_F,OPP_FT_PCT_G,OPP_OREB_C,OPP_OREB_F,OPP_OREB_G,OPP_DREB_C,OPP_DREB_F,OPP_DREB_G,OPP_REB_C,OPP_REB_F,OPP_REB_G,OPP_AST_C,OPP_AST_F,OPP_AST_G,OPP_TOV_C,OPP_TOV_F,OPP_TOV_G,OPP_STL_C,OPP_STL_F,OPP_STL_G,OPP_BLK_C,OPP_BLK_F,OPP_BLK_G,OPP_BLKA_C,OPP_BLKA_F,OPP_BLKA_G,OPP_PF_C,OPP_PF_F,OPP_PF_G,OPP_PFD_C,OPP_PFD_F,OPP_PFD_G,OPP_PTS_C,OPP_PTS_F,OPP_PTS_G,PLUS_MINUS_C_DEF,PLUS_MINUS_F_DEF,PLUS_MINUS_G_DEF
31941,2025-26,1610612755,PHI,0022500473,2026-01-01,PHI @ DAL,W,240,123,15,48,90,0.533,13,36,0.361,14,16,0.875,6,37,43,22,10,7,12,19,121.8,104.9,16.9,0.458,1.83,16.8,0.186,0.685,0.464,0.606,0.634,1.0,102.0,0.563,0.600,0.400,0.569,0.098,0.317,0.130,0.114,0.154,0.472,0.314,0.686,0.846,0.154,0.458,0.542,17.73,383,2,1,269,18,28,0.643,30,62,0.484,18,27,0.667,20,58,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31943,2025-26,1610612742,DAL,0022500473,2026-01-01,DAL vs. PHI,L,240,108,-15,42,94,0.447,6,28,0.214,18,20,0.900,7,32,39,23,8,1,13,12,104.9,121.8,-16.9,0.548,1.77,16.1,0.315,0.814,0.536,0.479,0.525,1.0,102.0,0.437,0.702,0.298,0.667,0.074,0.167,0.148,0.167,0.102,0.593,0.556,0.444,0.500,0.500,0.548,0.452,18.03,383,3,0,254,25,47,0.532,17,47,0.362,22,31,0.710,21,50,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31944,2025-26,1610612738,BOS,0022500474,2026-01-01,BOS @ SAC,W,240,120,14,44,87,0.506,17,41,0.415,15,18,0.833,5,35,40,25,8,6,13,12,127.7,111.6,16.1,0.568,1.92,18.7,0.349,0.783,0.573,0.603,0.632,1.0,94.5,0.553,0.529,0.471,0.450,0.033,0.425,0.075,0.125,0.075,0.417,0.407,0.593,0.824,0.176,0.568,0.432,18.64,400,3,1,284,14,24,0.583,30,63,0.476,13,19,0.684,26,57,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31945,2025-26,1610612746,LAC,0022500475,2026-01-01,LAC vs. UTA,W,240,118,17,40,89,0.449,16,51,0.314,22,26,0.846,16,31,47,20,8,7,13,22,120.4,103.1,17.3,0.500,1.54,14.6,0.373,0.739,0.546,0.539,0.587,1.0,98.0,0.576,0.427,0.573,0.407,0.085,0.407,0.093,0.186,0.297,0.322,0.375,0.625,0.688,0.313,0.500,0.500,17.98,374,3,0,250,12,25,0.480,28,64,0.438,20,28,0.714,33,52,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31946,2025-26,1610612762,UTA,0022500475,2026-01-01,UTA @ LAC,L,240,101,-17,36,78,0.462,6,27,0.222,23,30,0.767,7,28,35,20,7,5,18,21,103.1,120.4,-17.3,0.556,1.11,15.4,0.261,0.627,0.454,0.500,0.554,1.0,98.0,0.424,0.654,0.346,0.594,0.020,0.178,0.119,0.228,0.119,0.574,0.500,0.500,0.833,0.167,0.556,0.444,18.24,358,3,2,240,20,35,0.571,16,43,0.372,15,24,0.625,16,56,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31947,2025-26,1610612758,SAC,0022500474,2026-01-01,SAC vs. BOS,L,240,106,-14,40,85,0.471,12,36,0.333,14,15,0.933,8,24,32,29,7,2,9,17,111.6,127.7,-16.1,0.725,3.22,21.6,0.217,0.651,0.427,0.541,0.579,1.0,94.5,0.447,0.576,0.424,0.528,0.151,0.340,0.104,0.132,0.104,0.377,0.607,0.393,1.000,0.000,0.725,0.275,17.95,385,3,2,275,18,36,0.500,22,49,0.449,20,25,0.800,18,46,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:

conn.cursor()

conn.execute("DELETE FROM team_shot_location_boxscores where gameDate = '2026-01-01'")
conn.execute("DELETE FROM player_shot_location_boxscores where gameDate = '2026-01-01'")

display(pd.read_sql("SELECT * FROM team_shot_location_boxscores where gameDate = '2026-01-01'", conn))
display(pd.read_sql("SELECT * FROM player_shot_location_boxscores where gameDate = '2026-01-01'", conn))

conn.commit()

conn.close()

Empty DataFrame
Columns: [teamId, teamName, Restricted Area FGM, Restricted Area FGA, Restricted Area FG_PCT, In The Paint (Non-RA) FGM, In The Paint (Non-RA) FGA, In The Paint (Non-RA) FG_PCT, Mid-Range FGM, Mid-Range FGA, Mid-Range FG_PCT, Left Corner 3 FGM, Left Corner 3 FGA, Left Corner 3 FG_PCT, Right Corner 3 FGM, Right Corner 3 FGA, Right Corner 3 FG_PCT, Above the Break 3 FGM, Above the Break 3 FGA, Above the Break 3 FG_PCT, Backcourt FGM, Backcourt FGA, Backcourt FG_PCT, Corner 3 FGM, Corner 3 FGA, Corner 3 FG_PCT, season, gameDate]
Index: []

Empty DataFrame
Columns: [personId, playerName, teamId, teamTricode, AGE, NICKNAME, Restricted Area FGM, Restricted Area FGA, Restricted Area FG_PCT, In The Paint (Non-RA) FGM, In The Paint (Non-RA) FGA, In The Paint (Non-RA) FG_PCT, Mid-Range FGM, Mid-Range FGA, Mid-Range FG_PCT, Left Corner 3 FGM, Left Corner 3 FGA, Left Corner 3 FG_PCT, Right Corner 3 FGM, Right Corner 3 FGA, Right Corner 3 FG_PCT, Above the Break 3 FGM, Above the Break 3 FGA, Above the Break 3 FG_PCT, Backcourt FGM, Backcourt FGA, Backcourt FG_PCT, Corner 3 FGM, Corner 3 FGA, Corner 3 FG_PCT, season, gameDate]
Index: []

In [84]:
conn.commit()

In [79]:
from nba_api.stats.endpoints import leaguedashteamshotlocations

date = '2026-01-01'
season = '2025-26'
season_type = 'Regular Season'


stats = leaguedashteamshotlocations.LeagueDashTeamShotLocations(
    distance_range='By Zone',
    per_mode_detailed='PerGame',
    season=season,
    season_type_all_star=season_type,
    date_from_nullable=date,
    date_to_nullable=date,
)

In [81]:
stats.get_data_frames()[0]

SHOT_CATEGORY                                 Restricted Area               \
columns           TEAM_ID           TEAM_NAME             FGM   FGA FG_PCT
0              1610612738      Boston Celtics             4.0   6.0  0.667
1              1610612751       Brooklyn Nets            18.0  32.0  0.563
2              1610612742    Dallas Mavericks            18.0  30.0  0.600
3              1610612765     Detroit Pistons            20.0  27.0  0.741
4              1610612745     Houston Rockets            19.0  26.0  0.731
5              1610612746         LA Clippers            14.0  22.0  0.636
6              1610612748          Miami Heat            11.0  22.0  0.500
7              1610612755  Philadelphia 76ers            21.0  28.0  0.750
8              1610612758    Sacramento Kings             4.0   4.0  1.000
9              1610612762           Utah Jazz            21.0  28.0  0.750

SHOT_CATEGORY In The Paint (Non-RA)              Mid-Range               \
columns                         FGM   FGA FG_PCT       FGM   FGA FG_PCT
0                              21.0  31.0  0.677       2.0   9.0  0.222
1                               5.0  12.0  0.417       1.0   2.0  0.500
2                              14.0  21.0  0.667       4.0  14.0  0.286
3                               7.0  20.0  0.350       2.0   7.0  0.286
4                               8.0  14.0  0.571       8.0  13.0  0.615
5                               5.0   8.0  0.625       5.0   8.0  0.625
6                              15.0  29.0  0.517       3.0   9.0  0.333
7                               8.0  14.0  0.571       6.0  12.0  0.500
8                              16.0  30.0  0.533       8.0  15.0  0.533
9                               8.0  16.0  0.500       1.0   7.0  0.143

SHOT_CATEGORY Left Corner 3              Right Corner 3              \
columns                 FGM   FGA FG_PCT            FGM  FGA FG_PCT
0                       0.0   4.0  0.000            3.0  3.0  1.000
1                       1.0   2.0  0.500            1.0  4.0  0.250
2                       0.0   7.0  0.000            1.0  5.0  0.200
3                       1.0   2.0  0.500            1.0  4.0  0.250
4                       3.0   6.0  0.500            3.0  5.0  0.600
5                       3.0   5.0  0.600            3.0  5.0  0.600
6                       2.0   3.0  0.667            1.0  7.0  0.143
7                       3.0  10.0  0.300            1.0  3.0  0.333
8                       3.0   5.0  0.600            1.0  2.0  0.500
9                       5.0   9.0  0.556            1.0  5.0  0.200

SHOT_CATEGORY Above the Break 3              Backcourt             Corner 3  \
columns                     FGM   FGA FG_PCT       FGM  FGA FG_PCT      FGM
0                          14.0  34.0  0.412       0.0  0.0    0.0      3.0
1                           8.0  24.0  0.333       0.0  0.0    0.0      2.0
2                           5.0  17.0  0.294       0.0  0.0    0.0      1.0
3                           7.0  20.0  0.350       0.0  0.0    0.0      2.0
4                           6.0  18.0  0.333       0.0  0.0    0.0      6.0
5                          10.0  41.0  0.244       0.0  0.0    0.0      6.0
6                          11.0  29.0  0.379       0.0  0.0    0.0      3.0
7                           9.0  23.0  0.391       0.0  0.0    0.0      4.0
8                           8.0  29.0  0.276       0.0  0.0    0.0      4.0
9                           0.0  13.0  0.000       0.0  0.0    0.0      6.0

SHOT_CATEGORY
columns         FGA FG_PCT
0               7.0  0.429
1               6.0  0.333
2              12.0  0.083
3               6.0  0.333
4              11.0  0.545
5              10.0  0.600
6              10.0  0.300
7              13.0  0.308
8               7.0  0.571
9              14.0  0.429

In [97]:

map = {}
for i, row in tbs.groupby(['teamId', 'teamTricode']).size().reset_index().iterrows():
    map[row['teamTricode']] = row['teamId']

map

{'ATL': 1610612737,
 'BOS': 1610612738,
 'CLE': 1610612739,
 'NOP': 1610612740,
 'CHI': 1610612741,
 'DAL': 1610612742,
 'DEN': 1610612743,
 'GSW': 1610612744,
 'HOU': 1610612745,
 'LAC': 1610612746,
 'LAL': 1610612747,
 'MIA': 1610612748,
 'MIL': 1610612749,
 'MIN': 1610612750,
 'BKN': 1610612751,
 'NYK': 1610612752,
 'ORL': 1610612753,
 'IND': 1610612754,
 'PHI': 1610612755,
 'PHX': 1610612756,
 'POR': 1610612757,
 'SAC': 1610612758,
 'SAS': 1610612759,
 'OKC': 1610612760,
 'TOR': 1610612761,
 'UTA': 1610612762,
 'MEM': 1610612763,
 'WAS': 1610612764,
 'DET': 1610612765,
 'CHA': 1610612766}

In [21]:
pbs = pd.read_sql("SELECT * FROM player_basic_stats", conn)

pbs

,seasonYear,personId,playerName,NICKNAME,teamId,teamTricode,teamName,gameId,gameDate,MATCHUP,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG,MIN_SEC
0,2015-16,203493,Reggie Bullock Jr.,Reggie,1610612765,DET,Detroit Pistons,0021501220,2016-04-13T00:00:00,DET @ CLE,...,4972,4736,5598,3172,6050,2107,76,4936,1.0,38:27
1,2015-16,203210,JaMychal Green,JaMychal,1610612763,MEM,Memphis Grizzlies,0021501227,2016-04-13T00:00:00,MEM @ GSW,...,11390,7786,8086,23150,10000,2107,76,9378,1.0,26:00
2,2015-16,201976,Patrick Beverley,Patrick,1610612745,HOU,Houston Rockets,0021501224,2016-04-13T00:00:00,HOU vs. SAC,...,17641,7786,11389,328,881,2107,76,2174,1.0,32:51
3,2015-16,203089,John Henson,John,1610612749,MIL,Milwaukee Bucks,0021501225,2016-04-13T00:00:00,MIL vs. IND,...,11390,7786,14029,17477,16712,2107,76,15285,1.0,21:48
4,2015-16,203516,James Ennis III,James,1610612740,NOP,New Orleans Pelicans,0021501226,2016-04-13T00:00:00,NOP @ MIN,...,22104,2748,618,24301,4384,2107,76,2174,1.0,39:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339373,2025-26,1629020,Jarred Vanderbilt,Jarred,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21T00:00:00,LAL vs. GSW,...,1,7835,9946,7054,9796,836,63,9515,1.0,11:56
339374,2025-26,1642366,Quinten Post,Quinten,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21T00:00:00,GSW @ LAL,...,2289,5154,9946,3251,9991,836,63,10067,1.0,8:34
339375,2025-26,1642959,Chris Youngblood,Chris,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21T00:00:00,OKC vs. HOU,...,1,7835,9946,5260,10835,836,63,10849,1.0,0:06
339376,2025-26,1642964,Brooks Barnhizer,Brooks,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21T00:00:00,OKC vs. HOU,...,1,7835,9946,6214,10835,836,63,10849,1.0,2:15
339377,2025-26,1630611,Gui Santos,Gui,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21T00:00:00,GSW @ LAL,...,1,7835,9946,5260,11221,836,63,10849,1.0,2:39

In [28]:
pbs['gameDate'].max()

'2026-01-03T00:00:00'

In [25]:
from nba_api.stats.endpoints import playergamelogs

season = '2025-26'
season_type = 'Regular Season'

player_boxscores = playergamelogs.PlayerGameLogs(
    season_nullable=season,
    season_type_nullable=season_type
).get_data_frames()[0]

player_boxscores.tail()

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT
14246,2025-26,1629020,Jarred Vanderbilt,Jarred,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21T00:00:00,LAL vs. GSW,...,9847,12598,8908,12396,1034,68,12067,1,11:56,1
14247,2025-26,1642366,Quinten Post,Quinten,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21T00:00:00,GSW @ LAL,...,6414,12598,4115,12641,1034,68,12741,1,8:34,1
14248,2025-26,1642959,Chris Youngblood,Chris,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21T00:00:00,OKC vs. HOU,...,9847,12598,6629,13707,1034,68,13726,1,0:06,1
14249,2025-26,1642964,Brooks Barnhizer,Brooks,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21T00:00:00,OKC vs. HOU,...,9847,12598,7841,13707,1034,68,13726,1,2:15,1
14250,2025-26,1630611,Gui Santos,Gui,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21T00:00:00,GSW @ LAL,...,9847,12598,6629,14188,1034,68,13726,1,2:39,1

In [27]:
player_boxscores['GAME_DATE'].max()

'2026-01-21T00:00:00'

In [13]:
odds_archive = pd.read_csv('../data/nba_odds_archive.csv')
nba_odds = pd.read_sql("SELECT * FROM nba_odds", conn)

In [5]:
odds_archive['teamId_home'].nunique()
odds_archive.loc[odds_archive['teamId_home'].isnull()]

,season,date,home_team,away_team,home_1stQtr,away_1stQtr,home_2ndQtr,away_2ndQtr,home_3rdQtr,away_3rdQtr,...,away_open_spread,home_close_spread,away_close_spread,home_2H_spread,away_2H_spread,2H_total,open_over_under,close_over_under,teamId_home,teamId_away
1073,2011,20120621.0,0,Thunder,0,26,0,23,0,22,...,0.0,-0.0,0.0,-0.0,0.0,97.5,193.0,194.5,NaN,1.610613e+09
2387,2012,20130620.0,0,Spurs,0,16,0,28,0,27,...,0.0,-0.0,0.0,-0.0,0.0,95.0,191.0,188.0,NaN,1.610613e+09
3706,2013,20140615.0,0,Heat,0,29,0,11,0,18,...,0.0,-0.0,0.0,-0.0,0.0,101.0,195.0,197.5,NaN,1.610613e+09
5017,2014,20150616.0,0,Warriors,0,28,0,17,0,28,...,-0.0,0.0,-0.0,0.0,-0.0,2.5,4.5,3.0,NaN,1.610613e+09
6333,2015,20160619.0,0,Cavaliers,0,23,0,19,0,33,...,0.0,-0.0,0.0,-0.0,0.0,104.0,207.5,204.5,NaN,1.610613e+09
7642,2016,20170612.0,0,Cavaliers,0,37,0,23,0,33,...,0.0,-0.0,0.0,-0.0,0.0,111.5,230.5,231.0,NaN,1.610613e+09
8954,2017,20180608.0,0,Warriors,0,34,0,27,0,25,...,-0.0,0.0,-0.0,0.0,-0.0,1.0,5.5,4.5,NaN,1.610613e+09
10266,2018,20190613.0,0,Raptors,0,33,0,27,0,26,...,0.0,-0.0,0.0,-0.0,0.0,107.5,211.0,211.5,NaN,1.610613e+09
11409,2019,20191011.0,0,Lakers,0,28,0,36,0,23,...,-0.0,0.0,-0.0,0.0,-0.0,104.0,5.0,5.5,NaN,1.610613e+09
12580,2020,20210720.0,0,Suns,0,16,0,31,0,30,...,0.0,-0.0,0.0,-0.0,0.0,112.5,223.0,221.0,NaN,1.610613e+09
13903,2021,20220616.0,0,Golden State,0,27,0,27,0,22,...,0.0,-0.0,0.0,-0.0,0.0,103.5,212.5,211.5,NaN,1.610613e+09

In [141]:
nba_odds_deduped = nba_odds.drop_duplicates(subset=['gameDate', 'teamId_home', 'teamId_away'], keep='last')

In [149]:
nba_odds.loc[nba_odds.duplicated(subset=['gameDate', 'teamId_home', 'teamId_away'])]

Empty DataFrame
Columns: [gameDate, status, home_team, home_team_loc, home_team_abbr, home_team_rank, away_team, away_team_loc, away_team_abbr, away_team_rank, home_score, away_score, home_spread_betmgm, home_spread_fanduel, home_spread_caesars, home_spread_bet365, home_spread_draftkings, home_spread_bet_rivers_ny, home_spread_odds_betmgm, home_spread_odds_fanduel, home_spread_odds_caesars, home_spread_odds_bet365, home_spread_odds_draftkings, home_spread_odds_bet_rivers_ny, away_spread_betmgm, away_spread_fanduel, away_spread_caesars, away_spread_bet365, away_spread_draftkings, away_spread_bet_rivers_ny, away_spread_odds_betmgm, away_spread_odds_fanduel, away_spread_odds_caesars, away_spread_odds_bet365, away_spread_odds_draftkings, away_spread_odds_bet_rivers_ny, home_ml_betmgm, home_ml_fanduel, home_ml_caesars, home_ml_bet365, home_ml_draftkings, home_ml_bet_rivers_ny, away_ml_betmgm, away_ml_fanduel, away_ml_caesars, away_ml_bet365, away_ml_draftkings, away_ml_bet_rivers_ny, total_betmgm, total_fanduel, total_caesars, total_bet365, total_draftkings, total_bet_rivers_ny, over_odds_betmgm, over_odds_fanduel, over_odds_caesars, over_odds_bet365, over_odds_draftkings, over_odds_bet_rivers_ny, under_odds_betmgm, under_odds_fanduel, under_odds_caesars, under_odds_bet365, under_odds_draftkings, under_odds_bet_rivers_ny, season, derivedGameId, teamId_home, teamId_away]
Index: []

In [144]:
nba_odds_deduped.loc[nba_odds_deduped['teamId_home'].isna(), 'home_team_abbr'].value_counts()

Series([], Name: count, dtype: int64)

In [11]:
odds_archive.iloc[:, 14:-2].describe()

,home_close_ml,away_close_ml,home_open_spread,away_open_spread,home_close_spread,away_close_spread,home_2H_spread,away_2H_spread,2H_total,open_over_under,close_over_under
count,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000,14567.000000
mean,-240.504977,107.579186,-2.629232,2.629232,2.767214,-2.767214,-4.281115,4.281115,79.145193,210.284376,195.768758
std,688.868839,426.145809,6.739128,6.739128,55.980039,55.980039,52.111807,52.111807,45.479675,23.619704,54.516838
min,-13000.000000,-9900.000000,-216.000000,-18.500000,-242.500000,-242.500000,-124.000000,-122.500000,0.000000,4.500000,0.000000
25%,-330.000000,-145.000000,-7.000000,-2.500000,-8.000000,-3.500000,-6.500000,-3.000000,87.000000,199.500000,196.500000
50%,-165.000000,145.000000,-3.500000,3.500000,-4.000000,4.000000,-2.500000,2.500000,101.500000,211.000000,209.000000
75%,125.000000,270.000000,2.500000,7.000000,3.500000,8.000000,3.000000,6.500000,108.000000,221.000000,220.000000
max,2000.000000,4000.000000,18.500000,216.000000,242.500000,242.500000,122.500000,124.000000,1118.000000,1955.500000,251.000000

In [16]:
nba_odds[['home_spread_betmgm',
       'home_spread_fanduel', 'home_spread_caesars', 'home_spread_bet365',
       'home_spread_draftkings', 'home_spread_bet_rivers_ny',
       'home_spread_odds_betmgm', 'home_spread_odds_fanduel',
       'home_spread_odds_caesars', 'home_spread_odds_bet365',
       'home_spread_odds_draftkings', 'home_spread_odds_bet_rivers_ny',
       'away_spread_betmgm', 'away_spread_fanduel', 'away_spread_caesars',
       'away_spread_bet365', 'away_spread_draftkings',
       'away_spread_bet_rivers_ny', 'away_spread_odds_betmgm',
       'away_spread_odds_fanduel', 'away_spread_odds_caesars',
       'away_spread_odds_bet365', 'away_spread_odds_draftkings',
       'away_spread_odds_bet_rivers_ny', 'home_ml_betmgm', 'home_ml_fanduel',
       'home_ml_caesars', 'home_ml_bet365', 'home_ml_draftkings',
       'home_ml_bet_rivers_ny', 'away_ml_betmgm', 'away_ml_fanduel',
       'away_ml_caesars', 'away_ml_bet365', 'away_ml_draftkings',
       'away_ml_bet_rivers_ny', 'total_betmgm', 'total_fanduel',
       'total_caesars', 'total_bet365', 'total_draftkings',
       'total_bet_rivers_ny', 'over_odds_betmgm', 'over_odds_fanduel',
       'over_odds_caesars', 'over_odds_bet365', 'over_odds_draftkings',
       'over_odds_bet_rivers_ny', 'under_odds_betmgm', 'under_odds_fanduel',
       'under_odds_caesars', 'under_odds_bet365', 'under_odds_draftkings',
       'under_odds_bet_rivers_ny']].describe()

,home_spread_fanduel,home_spread_caesars,home_spread_bet365,home_spread_draftkings,home_spread_odds_fanduel,home_spread_odds_caesars,home_spread_odds_bet365,home_spread_odds_draftkings,away_spread_fanduel,away_spread_caesars,...,total_bet365,total_draftkings,over_odds_fanduel,over_odds_caesars,over_odds_bet365,over_odds_draftkings,under_odds_fanduel,under_odds_caesars,under_odds_bet365,under_odds_draftkings
count,8126.000000,7788.000000,8129.000000,8113.000000,8126.000000,7788.000000,8129.000000,8113.000000,8126.000000,7788.000000,...,8128.000000,8110.000000,8127.000000,7786.000000,8128.000000,8110.000000,8127.000000,7786.000000,8128.000000,8110.000000
mean,-2.039257,-2.044299,-2.055419,-2.051707,-137.503569,-107.962250,-109.899988,-108.616172,2.039257,2.044299,...,225.198142,225.140567,-102.268611,-108.851143,-109.875369,-110.480888,-171.582749,-108.758669,-109.892594,-110.441184
std,7.587435,7.261244,6.931135,7.551578,1663.391244,23.362655,6.152844,26.627995,7.587435,7.261244,...,9.332401,10.294886,176.242357,18.481529,5.884650,24.491958,2301.344100,16.891651,9.844136,18.505073
min,-44.500000,-40.500000,-24.500000,-44.500000,-100000.000000,-169.000000,-130.000000,-210.000000,-32.500000,-31.500000,...,195.500000,170.500000,-500.000000,-135.000000,-125.000000,-1600.000000,-100000.000000,-130.000000,-125.000000,-295.000000
25%,-7.500000,-7.000000,-7.000000,-7.500000,-112.000000,-110.000000,-110.000000,-114.000000,-3.500000,-3.500000,...,218.500000,218.500000,-110.000000,-110.000000,-110.000000,-113.000000,-110.000000,-110.000000,-110.000000,-113.000000
50%,-3.000000,-3.000000,-3.000000,-3.000000,-110.000000,-110.000000,-110.000000,-110.000000,3.000000,3.000000,...,225.000000,225.500000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000
75%,3.500000,3.500000,3.500000,3.500000,-108.000000,-110.000000,-110.000000,-110.000000,7.500000,7.000000,...,231.500000,232.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-110.000000,-109.000000
max,32.500000,31.500000,18.500000,31.500000,1000.000000,140.000000,100.000000,480.000000,44.500000,40.500000,...,265.500000,303.500000,8000.000000,105.000000,115.000000,230.000000,340.000000,110.000000,750.000000,800.000000

In [19]:
nba_odds.loc[nba_odds['home_spread_draftkings'].notnull(), 'season'].value_counts().sort_index()

season
2018-19      18
2019-20    1142
2020-21    1168
2021-22    1323
2022-23    1320
2023-24    1306
2024-25    1317
2025-26     519
Name: count, dtype: int64

In [20]:
nba_odds.columns

Index(['gameDate', 'status', 'home_team', 'home_team_loc', 'home_team_abbr',
       'home_team_rank', 'away_team', 'away_team_loc', 'away_team_abbr',
       'away_team_rank', 'home_score', 'away_score', 'home_spread_betmgm',
       'home_spread_fanduel', 'home_spread_caesars', 'home_spread_bet365',
       'home_spread_draftkings', 'home_spread_bet_rivers_ny',
       'home_spread_odds_betmgm', 'home_spread_odds_fanduel',
       'home_spread_odds_caesars', 'home_spread_odds_bet365',
       'home_spread_odds_draftkings', 'home_spread_odds_bet_rivers_ny',
       'away_spread_betmgm', 'away_spread_fanduel', 'away_spread_caesars',
       'away_spread_bet365', 'away_spread_draftkings',
       'away_spread_bet_rivers_ny', 'away_spread_odds_betmgm',
       'away_spread_odds_fanduel', 'away_spread_odds_caesars',
       'away_spread_odds_bet365', 'away_spread_odds_draftkings',
       'away_spread_odds_bet_rivers_ny', 'home_ml_betmgm', 'home_ml_fanduel',
       'home_ml_caesars', 'home_ml_bet365', 'home_ml_draftkings',
       'home_ml_bet_rivers_ny', 'away_ml_betmgm', 'away_ml_fanduel',
       'away_ml_caesars', 'away_ml_bet365', 'away_ml_draftkings',
       'away_ml_bet_rivers_ny', 'total_betmgm', 'total_fanduel',
       'total_caesars', 'total_bet365', 'total_draftkings',
       'total_bet_rivers_ny', 'over_odds_betmgm', 'over_odds_fanduel',
       'over_odds_caesars', 'over_odds_bet365', 'over_odds_draftkings',
       'over_odds_bet_rivers_ny', 'under_odds_betmgm', 'under_odds_fanduel',
       'under_odds_caesars', 'under_odds_bet365', 'under_odds_draftkings',
       'under_odds_bet_rivers_ny', 'season', 'derivedGameId', 'teamId_home',
       'teamId_away'],
      dtype='object')

In [30]:
training_v3 = pd.read_csv("../data/processed/training_set_v3.csv")

In [35]:
training_v3.groupby(['seasonYear', 'teamId_home']).size().reset_index()

    seasonYear  teamId_home   0
0      2013-14   1610612737  44
1      2013-14   1610612738  41
2      2013-14   1610612739  41
3      2013-14   1610612740  41
4      2013-14   1610612741  44
..         ...          ...  ..
385    2025-26   1610612762  22
386    2025-26   1610612763  21
387    2025-26   1610612764  20
388    2025-26   1610612765  21
389    2025-26   1610612766  20

[390 rows x 3 columns]

In [36]:
print(training_v3.columns)

Index(['teamId_home', 'gameDate', 'seasonYear', 'gameId',
       'off_fieldGoalsMade_5g_home', 'off_fieldGoalsMade_20g_home',
       'off_fieldGoalsMade_40g_home', 'off_fieldGoalsAttempted_5g_home',
       'off_fieldGoalsAttempted_20g_home', 'off_fieldGoalsAttempted_40g_home',
       ...
       'roster_bpm_away', 'roster_bpm_ewma_y', 'odds_away_ml',
       'odds_away_spread', 'odds_away_spread_open', 'odds_home_ml',
       'odds_home_spread', 'odds_home_spread_open', 'odds_total',
       'odds_total_open'],
      dtype='object', length=870)

In [41]:
tbs = pd.read_sql("""select * from team_basic_stats""", conn)

tbs.columns

Index(['SEASON_ID', 'teamId', 'teamTricode', 'teamName', 'gameId', 'gameDate',
       'MATCHUP', 'WL', 'minutes', 'fieldGoalsMade', 'fieldGoalsAttempted',
       'fieldGoalPercentage', 'threePointersMade', 'threePointersAttempted',
       'threePointerPercentage', 'freeThrowsMade', 'freeThrowsAttempted',
       'freeThrowPercentage', 'offensiveRebounds', 'defensiveRebounds',
       'rebounds', 'assists', 'steals', 'blocks', 'turnovers', 'personalFouls',
       'points', 'plusMinus', 'seasonYear'],
      dtype='object')

In [ ]:
matchups = pd.read_sql("""SELECT 
                    h.gameId,
                    h.gameDate,
                    h.teamId as home_teamId,
                    h.teamName AS home_team,
                    h.points AS home_score,
                    a.teamId as away_teamId,
                    a.teamName AS away_team,
                    a.points AS away_score
                FROM team_basic_stats h
                JOIN team_basic_stats a 
                    ON h.gameId = a.gameId 
                    AND h.teamId != a.teamId
                WHERE h.matchup LIKE '%vs.%'
                AND h.WL IS NOT NULL""", conn)

matchups

,gameId,gameDate,home_teamId,home_team,home_score,away_teamId,away_team,away_score
0,0021300003,2013-10-29,1610612747,Los Angeles Lakers,116,1610612746,Los Angeles Clippers,103
1,0021300002,2013-10-29,1610612748,Miami Heat,107,1610612741,Chicago Bulls,95
2,0021300001,2013-10-29,1610612754,Indiana Pacers,97,1610612753,Orlando Magic,87
3,0021300004,2013-10-30,1610612739,Cleveland Cavaliers,98,1610612751,Brooklyn Nets,94
4,0021300010,2013-10-30,1610612750,Minnesota Timberwolves,120,1610612753,Orlando Magic,115
...,...,...,...,...,...,...,...,...
16122,0022500630,2026-01-22,1610612742,Dallas Mavericks,123,1610612744,Golden State Warriors,115
16123,0022500631,2026-01-22,1610612750,Minnesota Timberwolves,115,1610612741,Chicago Bulls,120
16124,0022500632,2026-01-22,1610612762,Utah Jazz,109,1610612759,San Antonio Spurs,126
16125,0022500634,2026-01-22,1610612757,Portland Trail Blazers,127,1610612748,Miami Heat,110
16126,0022500633,2026-01-22,1610612746,LA Clippers,112,1610612747,Los Angeles Lakers,104

In [43]:
matchups['gameId'].nunique()

16127

In [53]:
from nba_api.stats.endpoints import scoreboardv3
from datetime import datetime

def get_nba_schedule(game_date=None):
    """
    Get today's games with official NBA gameIds.
    Returns DataFrame with gameId, home_team, away_team, gameDate.
    """
    if game_date is None:
        game_date = datetime.now().strftime('%Y-%m-%d')
    
    try:
        sb = scoreboardv3.ScoreboardV3(game_date=game_date)
        games = sb.get_normalized_dict()['GameHeader']
        
        if not games:
            return pd.DataFrame()
        
        records = []
        for g in games:
            records.append({
                'gameId': str(g['gameId']),
                'gameDate': game_date,
                'home_team': g['homeTeamName'],  # Check actual key names
                'away_team': g['awayTeamName'],
                'gameStatus': g.get('gameStatus', 1)
            })
        
        return pd.DataFrame(records)
    
    except Exception as e:
        return pd.DataFrame()

In [54]:
get_nba_schedule(game_date='2026-01-23')

Empty DataFrame
Columns: []
Index: []

In [61]:
game_date='2026-01-23'
sb = scoreboardv3.ScoreboardV3(game_date=game_date)
games = sb.get_data_frames()[1]

In [66]:
games['gameDate'] = games['gameTimeUTC'].str[:10]
games['triTeamcode_away'] = games['gameCode'].str[-6:-3]
games['triTeamcode_home'] = games['gameCode'].str[-3:]
games

,gameId,gameCode,gameStatus,gameStatusText,period,gameClock,gameTimeUTC,gameEt,regulationPeriods,seriesGameNumber,...,ifNecessary,seriesConference,poRoundDesc,gameSubtype,isNeutral,gameDate,triTeamCode_away,triTeamCode_home,triTeamcode_away,triTeamcode_home
0,0022500635,20260123/HOUDET,3,Final,4,,2026-01-24T00:00:00Z,2026-01-23T19:00:00Z,4,,...,False,,,,False,2026-01-24,HOU,DET,HOU,DET
1,0022500636,20260123/PHXATL,3,Final,4,,2026-01-24T00:30:00Z,2026-01-23T19:30:00Z,4,,...,False,,,,False,2026-01-24,PHX,ATL,PHX,ATL
2,0022500637,20260123/BOSBKN,3,Final/OT2,6,,2026-01-24T00:30:00Z,2026-01-23T19:30:00Z,4,,...,False,,,,False,2026-01-24,BOS,BKN,BOS,BKN
3,0022500638,20260123/SACCLE,3,Final,4,,2026-01-24T00:30:00Z,2026-01-23T19:30:00Z,4,,...,False,,,,False,2026-01-24,SAC,CLE,SAC,CLE
4,0022500639,20260123/NOPMEM,3,Final,4,,2026-01-24T01:00:00Z,2026-01-23T20:00:00Z,4,,...,False,,,,False,2026-01-24,NOP,MEM,NOP,MEM
5,0022500641,20260123/INDOKC,3,Final,4,,2026-01-24T01:00:00Z,2026-01-23T20:00:00Z,4,,...,False,,,,False,2026-01-24,IND,OKC,IND,OKC
6,0022500640,20260123/DENMIL,2,2nd Qtr,2,PT01M22.00S,2026-01-24T02:30:00Z,2026-01-23T21:30:00Z,4,,...,False,,,,False,2026-01-24,DEN,MIL,DEN,MIL
7,0022500642,20260123/TORPOR,2,End of 1st Qtr,1,PT00M00.00S,2026-01-24T03:00:00Z,2026-01-23T22:00:00Z,4,,...,False,,,,False,2026-01-24,TOR,POR,TOR,POR

In [67]:
from sbrscrape import Scoreboard

sb = Scoreboard(sport='NBA', date='2026-01-23')

sb.games

[{'date': '2026-01-24T00:00:00+00:00',
  'status': 'Final',
  'home_team': 'Detroit Pistons',
  'home_team_loc': 'Detroit',
  'home_team_abbr': 'DET',
  'home_team_rank': -1,
  'away_team': 'Houston Rockets',
  'away_team_loc': 'Houston',
  'away_team_abbr': 'HOU',
  'away_team_rank': -1,
  'home_score': 104,
  'away_score': 111,
  'home_spread': {'betmgm': -4.5,
   'fanduel': -4,
   'caesars': -4,
   'bet365': -4.5,
   'draftkings': -4.5,
   'fanatics': -4.5},
  'home_spread_odds': {'betmgm': -105,
   'fanduel': -108,
   'caesars': -110,
   'bet365': -105,
   'draftkings': -110,
   'fanatics': -110},
  'away_spread': {'betmgm': 4.5,
   'fanduel': 4,
   'caesars': 4,
   'bet365': 4.5,
   'draftkings': 4.5,
   'fanatics': 4.5},
  'away_spread_odds': {'betmgm': -115,
   'fanduel': -112,
   'caesars': -110,
   'bet365': -115,
   'draftkings': -110,
   'fanatics': -110},
  'under_odds': {'betmgm': -115,
   'fanduel': -106,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -112,
   'fanatics': -110},
  'over_odds': {'betmgm': -105,
   'fanduel': -116,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -108,
   'fanatics': -110},
  'total': {'betmgm': 217.5,
   'fanduel': 216.5,
   'caesars': 216.5,
   'bet365': 216.5,
   'draftkings': 217.5,
   'fanatics': 217},
  'home_ml': {'betmgm': -185,
   'fanduel': -176,
   'caesars': -190,
   'bet365': -180,
   'draftkings': -175,
   'fanatics': -180},
  'away_ml': {'betmgm': 150,
   'fanduel': 148,
   'caesars': 158,
   'bet365': 150,
   'draftkings': 145,
   'fanatics': 150}},
 {'date': '2026-01-24T00:30:00+00:00',
  'status': 'Final',
  'home_team': 'Atlanta Hawks',
  'home_team_loc': 'Atlanta',
  'home_team_abbr': 'ATL',
  'home_team_rank': -1,
  'away_team': 'Phoenix Suns',
  'away_team_loc': 'Phoenix',
  'away_team_abbr': 'PHO',
  'away_team_rank': -1,
  'home_score': 110,
  'away_score': 103,
  'home_spread': {'betmgm': 2.5,
   'fanduel': 3,
   'caesars': 3,
   'bet365': 3,
   'draftkings': 3.5,
   'fanatics': 3},
  'home_spread_odds': {'betmgm': -105,
   'fanduel': -110,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -115,
   'fanatics': -110},
  'away_spread': {'betmgm': -2.5,
   'fanduel': -3,
   'caesars': -3,
   'bet365': -3,
   'draftkings': -3.5,
   'fanatics': -3},
  'away_spread_odds': {'betmgm': -115,
   'fanduel': -110,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -105,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -112,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -108,
   'fanatics': -110},
  'total': {'betmgm': 233.5,
   'fanduel': 233.5,
   'caesars': 233.5,
   'bet365': 233.5,
   'draftkings': 233.5,
   'fanatics': 233.5},
  'home_ml': {'betmgm': 125,
   'fanduel': 122,
   'caesars': 130,
   'bet365': 125,
   'draftkings': 124,
   'fanatics': 125},
  'away_ml': {'betmgm': -150,
   'fanduel': -144,
   'caesars': -155,
   'bet365': -150,
   'draftkings': -148,
   'fanatics': -150}},
 {'date': '2026-01-24T00:30:00+00:00',
  'status': 'Final',
  'home_team': 'Cleveland Cavaliers',
  'home_team_loc': 'Cleveland',
  'home_team_abbr': 'CLE',
  'home_team_rank': -1,
  'away_team': 'Sacramento Kings',
  'away_team_loc': 'Sacramento',
  'away_team_abbr': 'SAC',
  'away_team_rank': -1,
  'home_score': 123,
  'away_score': 118,
  'home_spread': {'betmgm': -13.5,
   'fanduel': -13,
   'caesars': -13,
   'bet365': -13,
   'draftkings': -12.5,
   'fanatics': -13},
  'home_spread_odds': {'betmgm': -105,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -115,
   'fanatics': -110},
  'away_spread': {'betmgm': 13.5,
   'fanduel': 13,
   'caesars': 13,
   'bet365': 13,
   'draftkings': 12.5,
   'fanatics': 13},
  'away_spread_odds': {'betmgm': -115,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -105,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -114,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -112,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -108,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -108,
   'fanatics': -110},
  'total': {'betmgm': 233.5,
   'fanduel': 233.5,
   'caesars': 234,
   'bet365': 233.5,
   'draftkings': 233.5,
   'fanatics': 233},
  'home_ml': {'betmgm': -625,
   'fanduel': -649,
   'caesars': -599,
   'bet365': -578,
   'draftkings': -575,
   'fanatics': -629},
  'away_ml': {'betmgm': 450,
   'fanduel': 480,
   'caesars': 430,
   'bet365': 425,
   'draftkings': 425,
   'fanatics': 450}},
 {'date': '2026-01-24T00:30:00+00:00',
  'status': 'End',
  'home_team': 'Brooklyn Nets',
  'home_team_loc': 'Brooklyn',
  'home_team_abbr': 'BK',
  'home_team_rank': -1,
  'away_team': 'Boston Celtics',
  'away_team_loc': 'Boston',
  'away_team_abbr': 'BOS',
  'away_team_rank': -1,
  'home_score': 118,
  'away_score': 118,
  'home_spread': {'betmgm': 8.5,
   'fanduel': 8.5,
   'caesars': 8,
   'bet365': 8,
   'draftkings': 8.5,
   'fanatics': 8},
  'home_spread_odds': {'betmgm': -110,
   'fanduel': -112,
   'caesars': -105,
   'bet365': -105,
   'draftkings': -118,
   'fanatics': -110},
  'away_spread': {'betmgm': -8.5,
   'fanduel': -8.5,
   'caesars': -8,
   'bet365': -8,
   'draftkings': -8.5,
   'fanatics': -8},
  'away_spread_odds': {'betmgm': -110,
   'fanduel': -108,
   'caesars': -115,
   'bet365': -115,
   'draftkings': -102,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -106,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -112,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -114,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -108,
   'fanatics': -110},
  'total': {'betmgm': 215.5,
   'fanduel': 214.5,
   'caesars': 215.5,
   'bet365': 215.5,
   'draftkings': 215.5,
   'fanatics': 215},
  'home_ml': {'betmgm': 280,
   'fanduel': 285,
   'caesars': 278,
   'bet365': 275,
   'draftkings': 280,
   'fanatics': 260},
  'away_ml': {'betmgm': -350,
   'fanduel': -350,
   'caesars': -355,
   'bet365': -351,
   'draftkings': -355,
   'fanatics': -350}},
 {'date': '2026-01-24T01:00:00+00:00',
  'status': '03:20 4th',
  'home_team': 'Oklahoma City Thunder',
  'home_team_loc': 'Oklahoma City',
  'home_team_abbr': 'OKC',
  'home_team_rank': -1,
  'away_team': 'Indiana Pacers',
  'away_team_loc': 'Indiana',
  'away_team_abbr': 'IND',
  'away_team_rank': -1,
  'home_score': 102,
  'away_score': 107,
  'home_spread': {'betmgm': -15.5,
   'fanduel': -15.5,
   'caesars': -15.5,
   'bet365': -15.5,
   'draftkings': -15.5,
   'fanatics': -15.5},
  'home_spread_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -105,
   'draftkings': -110,
   'fanatics': -110},
  'away_spread': {'betmgm': 15.5,
   'fanduel': 15.5,
   'caesars': 15.5,
   'bet365': 15.5,
   'draftkings': 15.5,
   'fanatics': 15.5},
  'away_spread_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -115,
   'draftkings': -110,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'total': {'betmgm': 226.5,
   'fanduel': 226.5,
   'caesars': 226.5,
   'bet365': 226.5,
   'draftkings': 226.5,
   'fanatics': 226.5},
  'home_ml': {'betmgm': -1000,
   'fanduel': -1099,
   'caesars': -901,
   'bet365': -901,
   'draftkings': -901,
   'fanatics': -901},
  'away_ml': {'betmgm': 625,
   'fanduel': 700,
   'caesars': 600,
   'bet365': 600,
   'draftkings': 600,
   'fanatics': 600}},
 {'date': '2026-01-24T01:00:00+00:00',
  'status': '04:24 4th',
  'home_team': 'Memphis Grizzlies',
  'home_team_loc': 'Memphis',
  'home_team_abbr': 'MEM',
  'home_team_rank': -1,
  'away_team': 'New Orleans Pelicans',
  'away_team_loc': 'New Orleans',
  'away_team_abbr': 'NO',
  'away_team_rank': -1,
  'home_score': 112,
  'away_score': 115,
  'home_spread': {'betmgm': -4.5,
   'fanduel': -5,
   'caesars': -5,
   'bet365': -5,
   'draftkings': -5.5,
   'fanatics': -5},
  'home_spread_odds': {'betmgm': -115,
   'fanduel': -112,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -104,
   'fanatics': -110},
  'away_spread': {'betmgm': 4.5,
   'fanduel': 5,
   'caesars': 5,
   'bet365': 5,
   'draftkings': 5.5,
   'fanatics': 5},
  'away_spread_odds': {'betmgm': -105,
   'fanduel': -108,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -120,
   'fanatics': -110},
  'under_odds': {'betmgm': -115,
   'fanduel': -110,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -107,
   'fanatics': -110},
  'over_odds': {'betmgm': -105,
   'fanduel': -110,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -116,
   'fanatics': -110},
  'total': {'betmgm': 240.5,
   'fanduel': 240.5,
   'caesars': 240,
   'bet365': 240,
   'draftkings': 239.5,
   'fanatics': 240},
  'home_ml': {'betmgm': -200,
   'fanduel': -196,
   'caesars': -195,
   'bet365': -200,
   'draftkings': -198,
   'fanatics': -200},
  'away_ml': {'betmgm': 165,
   'fanduel': 164,
   'caesars': 162,
   'bet365': 165,
   'draftkings': 164,
   'fanatics': 165}},
 {'date': '2026-01-24T02:30:00+00:00',
  'status': '10:11 2nd',
  'home_team': 'Milwaukee Bucks',
  'home_team_loc': 'Milwaukee',
  'home_team_abbr': 'MIL',
  'home_team_rank': -1,
  'away_team': 'Denver Nuggets',
  'away_team_loc': 'Denver',
  'away_team_abbr': 'DEN',
  'away_team_rank': -1,
  'home_score': 23,
  'away_score': 23,
  'home_spread': {'betmgm': -9.5,
   'fanduel': -9,
   'caesars': -9,
   'bet365': -8.5,
   'draftkings': -8.5,
   'fanatics': -8.5},
  'home_spread_odds': {'betmgm': -102,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -115,
   'draftkings': -115,
   'fanatics': -110},
  'away_spread': {'betmgm': 9.5,
   'fanduel': 9,
   'caesars': 9,
   'bet365': 8.5,
   'draftkings': 8.5,
   'fanatics': 8.5},
  'away_spread_odds': {'betmgm': -118,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -105,
   'draftkings': -105,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -110,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'total': {'betmgm': 213.5,
   'fanduel': 213.5,
   'caesars': 213.5,
   'bet365': 213.5,
   'draftkings': 213.5,
   'fanatics': 213.5},
  'home_ml': {'betmgm': -325,
   'fanduel': -330,
   'caesars': -350,
   'bet365': -315,
   'draftkings': -325,
   'fanatics': -325},
  'away_ml': {'betmgm': 260,
   'fanduel': 265,
   'caesars': 275,
   'bet365': 255,
   'draftkings': 260,
   'fanatics': 250}},
 {'date': '2026-01-24T03:00:00+00:00',
  'status': '09:45 1st',
  'home_team': 'Portland Trail Blazers',
  'home_team_loc': 'Portland',
  'home_team_abbr': 'POR',
  'home_team_rank': -1,
  'away_team': 'Toronto Raptors',
  'away_team_loc': 'Toronto',
  'away_team_abbr': 'TOR',
  'away_team_rank': -1,
  'home_score': 0,
  'away_score': 3,
  'home_spread': {'betmgm': 3.5,
   'fanduel': 4,
   'caesars': 4,
   'bet365': 3.5,
   'draftkings': 3.5,
   'fanatics': 4},
  'home_spread_odds': {'betmgm': -105,
   'fanduel': -110,
   'caesars': -115,
   'bet365': -110,
   'draftkings': -105,
   'fanatics': -110},
  'away_spread': {'betmgm': -3.5,
   'fanduel': -4,
   'caesars': -4,
   'bet365': -3.5,
   'draftkings': -3.5,
   'fanatics': -4},
  'away_spread_odds': {'betmgm': -115,
   'fanduel': -110,
   'caesars': -105,
   'bet365': -110,
   'draftkings': -115,
   'fanatics': -110},
  'under_odds': {'betmgm': -110,
   'fanduel': -114,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'over_odds': {'betmgm': -110,
   'fanduel': -108,
   'caesars': -110,
   'bet365': -110,
   'draftkings': -110,
   'fanatics': -110},
  'total': {'betmgm': 225.5,
   'fanduel': 224.5,
   'caesars': 225,
   'bet365': 225.5,
   'draftkings': 225.5,
   'fanatics': 225.5},
  'home_ml': {'betmgm': 140,
   'fanduel': 132,
   'caesars': 143,
   'bet365': 135,
   'draftkings': 142,
   'fanatics': 130},
  'away_ml': {'betmgm': -170,
   'fanduel': -156,
   'caesars': -170,
   'bet365': -160,
   'draftkings': -170,
   'fanatics': -160}}]

In [74]:
sorted(nba_odds['home_team_abbr'].unique().tolist())

['ATL',
 'BK',
 'BKN',
 'BOS',
 'CHA',
 'CHAR',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GS',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NO',
 'NOP',
 'NY',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHO',
 'PHX',
 'POR',
 'SA',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS']

In [75]:
sorted(tbs['teamTricode'].unique().tolist())

['ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS']

In [6]:

tbs = pd.read_sql("""select * from team_basic_stats""", conn)
preds = pd.read_sql("""select * from predictions_log_v2""", conn)
preds

,game_id,game_date,prediction_date,home_team,away_team,matchup,ml_prob,spread_pred,total_pred,odds_home_ml,odds_away_ml,odds_home_spread,odds_total,home_score,away_score,status
0,0022500002,2025-10-21,2026-01-28 10:49:11,Los Angeles Lakers,Golden State Warriors,Golden State Warriors @ Los Angeles Lakers,0.462810,0.135529,231.048575,114.0,-145.0,2.5,226.5,109.0,119.0,COMPLETED
1,0022500001,2025-10-21,2026-01-28 10:49:11,Oklahoma City Thunder,Houston Rockets,Houston Rockets @ Oklahoma City Thunder,0.630542,7.676902,229.801994,-245.0,200.0,-6.5,225.5,125.0,124.0,COMPLETED
2,0022500089,2025-10-22,2026-01-28 10:49:11,Portland Trail Blazers,Minnesota Timberwolves,Minnesota Timberwolves @ Portland Trail Blazers,0.295775,-1.699020,222.166470,190.0,-250.0,5.5,222.5,114.0,118.0,COMPLETED
3,0022500084,2025-10-22,2026-01-28 10:49:11,Chicago Bulls,Detroit Pistons,Detroit Pistons @ Chicago Bulls,0.295775,-2.646268,233.217798,130.0,-155.0,2.5,236.5,115.0,111.0,COMPLETED
4,0022500086,2025-10-22,2026-01-28 10:49:11,Milwaukee Bucks,Washington Wizards,Washington Wizards @ Milwaukee Bucks,0.722222,10.219879,235.457466,-600.0,390.0,-11.5,227.5,133.0,120.0,COMPLETED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,0022500666,2026-01-27,2026-01-29 17:38:50,Philadelphia 76ers,Milwaukee Bucks,Milwaukee Bucks @ Philadelphia 76ers,0.741176,8.512548,220.299285,-375.0,295.0,-9.5,219.5,NaN,NaN,PENDING
705,0022500667,2026-01-27,2026-01-29 17:38:50,Oklahoma City Thunder,New Orleans Pelicans,New Orleans Pelicans @ Oklahoma City Thunder,0.809917,12.443270,234.374587,-847.0,575.0,-14.5,233.5,NaN,NaN,PENDING
706,0022500668,2026-01-27,2026-01-29 17:38:50,Denver Nuggets,Detroit Pistons,Detroit Pistons @ Denver Nuggets,0.182243,-3.715492,217.092630,215.0,-265.0,7.5,215.5,NaN,NaN,PENDING
707,0022500669,2026-01-27,2026-01-29 17:38:50,Phoenix Suns,Brooklyn Nets,Brooklyn Nets @ Phoenix Suns,0.741176,6.249533,207.892853,-310.0,250.0,-7.5,210.5,NaN,NaN,PENDING
708,0022500670,2026-01-27,2026-01-29 17:38:50,Utah Jazz,LA Clippers,LA Clippers @ Utah Jazz,0.182243,-4.833058,235.520814,270.0,-340.0,8.5,234.5,NaN,NaN,PENDING

In [18]:
preds.sort_values('game_date', ascending=False)

,game_id,game_date,prediction_date,home_team,away_team,matchup,ml_prob,spread_pred,total_pred,odds_home_ml,odds_away_ml,odds_home_spread,odds_total,home_score,away_score,status
689,0022500529,2026-01-29,2026-01-29 09:38:14,Chicago Bulls,Miami Heat,Miami Heat @ Chicago Bulls,0.427793,-0.742056,237.384320,110.0,-130.0,1.5,237.5,NaN,NaN,PENDING
692,0022500684,2026-01-29,2026-01-29 09:38:14,Denver Nuggets,Brooklyn Nets,Brooklyn Nets @ Denver Nuggets,0.622711,5.767909,208.607251,-278.0,225.0,-7.5,209.5,NaN,NaN,PENDING
694,0022500686,2026-01-29,2026-01-29 09:38:14,Minnesota Timberwolves,Oklahoma City Thunder,Oklahoma City Thunder @ Minnesota Timberwolves,0.182243,-5.330511,228.917664,195.0,-238.0,6.5,224.5,NaN,NaN,PENDING
691,0022500683,2026-01-29,2026-01-29 09:38:14,Dallas Mavericks,Charlotte Hornets,Charlotte Hornets @ Dallas Mavericks,0.278027,-4.095635,228.132539,145.0,-175.0,4.5,226.5,NaN,NaN,PENDING
690,0022500682,2026-01-29,2026-01-29 09:38:14,Atlanta Hawks,Houston Rockets,Houston Rockets @ Atlanta Hawks,0.427793,-1.550005,224.215195,136.0,-162.0,3.5,223.5,NaN,NaN,PENDING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,0022500003,2025-10-22,2026-01-28 10:49:12,New York Knicks,Cleveland Cavaliers,Cleveland Cavaliers @ New York Knicks,0.380952,-1.845598,226.494324,110.0,-130.0,1.5,229.5,119.0,111.0,COMPLETED
2,0022500089,2025-10-22,2026-01-28 10:49:11,Portland Trail Blazers,Minnesota Timberwolves,Minnesota Timberwolves @ Portland Trail Blazers,0.295775,-1.699020,222.166470,190.0,-250.0,5.5,222.5,114.0,118.0,COMPLETED
3,0022500084,2025-10-22,2026-01-28 10:49:11,Chicago Bulls,Detroit Pistons,Detroit Pistons @ Chicago Bulls,0.295775,-2.646268,233.217798,130.0,-155.0,2.5,236.5,115.0,111.0,COMPLETED
1,0022500001,2025-10-21,2026-01-28 10:49:11,Oklahoma City Thunder,Houston Rockets,Houston Rockets @ Oklahoma City Thunder,0.630542,7.676902,229.801994,-245.0,200.0,-6.5,225.5,125.0,124.0,COMPLETED
0,0022500002,2025-10-21,2026-01-28 10:49:11,Los Angeles Lakers,Golden State Warriors,Golden State Warriors @ Los Angeles Lakers,0.462810,0.135529,231.048575,114.0,-145.0,2.5,226.5,109.0,119.0,COMPLETED

In [19]:
preds.loc[preds['game_date'].isin(dates)]

,game_id,game_date,prediction_date,home_team,away_team,matchup,ml_prob,spread_pred,total_pred,odds_home_ml,odds_away_ml,odds_home_spread,odds_total,home_score,away_score,status
695,0022500659,2026-01-26,2026-01-29 17:38:44,Atlanta Hawks,Indiana Pacers,Indiana Pacers @ Atlanta Hawks,0.622711,6.726081,234.900398,-225.0,185.0,-5.5,234.5,NaN,NaN,PENDING
696,0022500657,2026-01-26,2026-01-29 17:38:44,Charlotte Hornets,Philadelphia 76ers,Philadelphia 76ers @ Charlotte Hornets,0.693548,2.088584,231.109855,-122.0,102.0,-1.5,229.5,NaN,NaN,PENDING
697,0022500658,2026-01-26,2026-01-29 17:38:44,Cleveland Cavaliers,Orlando Magic,Orlando Magic @ Cleveland Cavaliers,0.567663,3.326237,222.389842,-205.0,170.0,-4.5,223.5,NaN,NaN,PENDING
698,0022500660,2026-01-26,2026-01-29 17:38:44,Boston Celtics,Portland Trail Blazers,Portland Trail Blazers @ Boston Celtics,0.622711,8.768381,226.529663,-345.0,275.0,-8.5,223.5,NaN,NaN,PENDING
699,0022500661,2026-01-26,2026-01-29 17:38:44,Chicago Bulls,Los Angeles Lakers,Los Angeles Lakers @ Chicago Bulls,0.427793,-1.419828,238.407399,100.0,-120.0,1.5,235.5,NaN,NaN,PENDING
700,0022500662,2026-01-26,2026-01-29 17:38:44,Houston Rockets,Memphis Grizzlies,Memphis Grizzlies @ Houston Rockets,0.741176,9.625763,228.767997,-521.0,390.0,-10.5,225.5,NaN,NaN,PENDING
701,0022500663,2026-01-26,2026-01-29 17:38:44,Minnesota Timberwolves,Golden State Warriors,Golden State Warriors @ Minnesota Timberwolves,0.622711,9.249376,227.036068,-298.0,240.0,-8.5,226.5,NaN,NaN,PENDING
702,0022500664,2026-01-27,2026-01-29 17:38:50,Washington Wizards,Portland Trail Blazers,Portland Trail Blazers @ Washington Wizards,0.278027,-3.865137,234.009691,210.0,-258.0,6.5,232.5,NaN,NaN,PENDING
703,0022500665,2026-01-27,2026-01-29 17:38:50,New York Knicks,Sacramento Kings,Sacramento Kings @ New York Knicks,0.741176,13.913769,227.874614,-800.0,550.0,-14.5,225.5,NaN,NaN,PENDING
704,0022500666,2026-01-27,2026-01-29 17:38:50,Philadelphia 76ers,Milwaukee Bucks,Milwaukee Bucks @ Philadelphia 76ers,0.741176,8.512548,220.299285,-375.0,295.0,-9.5,219.5,NaN,NaN,PENDING
705,0022500667,2026-01-27,2026-01-29 17:38:50,Oklahoma City Thunder,New Orleans Pelicans,New Orleans Pelicans @ Oklahoma City Thunder,0.809917,12.443270,234.374587,-847.0,575.0,-14.5,233.5,NaN,NaN,PENDING
706,0022500668,2026-01-27,2026-01-29 17:38:50,Denver Nuggets,Detroit Pistons,Detroit Pistons @ Denver Nuggets,0.182243,-3.715492,217.092630,215.0,-265.0,7.5,215.5,NaN,NaN,PENDING
707,0022500669,2026-01-27,2026-01-29 17:38:50,Phoenix Suns,Brooklyn Nets,Brooklyn Nets @ Phoenix Suns,0.741176,6.249533,207.892853,-310.0,250.0,-7.5,210.5,NaN,NaN,PENDING
708,0022500670,2026-01-27,2026-01-29 17:38:50,Utah Jazz,LA Clippers,LA Clippers @ Utah Jazz,0.182243,-4.833058,235.520814,270.0,-340.0,8.5,234.5,NaN,NaN,PENDING

In [17]:
matchups = pd.merge(tbs, tbs, on=['gameId'], suffixes=('', '_x'))
matchups = matchups.loc[matchups['teamId']!=matchups['teamId_x']]
matchups = matchups.loc[matchups['MATCHUP'].str.contains('vs.')]

cols = ['MATCHUP', 'gameId', 'gameDate', 'teamName', 'teamName_x', 'points', 'points_x']
dates = ['2026-01-26', '2026-01-27']
matchups.loc[matchups['gameDate'].isin(dates), cols]

,MATCHUP,gameId,gameDate,teamName,teamName_x,points,points_x
64630,CHA vs. PHI,0022500657,2026-01-26,Charlotte Hornets,Philadelphia 76ers,130,93
64635,BOS vs. POR,0022500660,2026-01-26,Boston Celtics,Portland Trail Blazers,102,94
64638,MIN vs. GSW,0022500663,2026-01-26,Minnesota Timberwolves,Golden State Warriors,108,83
64642,ATL vs. IND,0022500659,2026-01-26,Atlanta Hawks,Indiana Pacers,132,116
64645,CLE vs. ORL,0022500658,2026-01-26,Cleveland Cavaliers,Orlando Magic,114,98
64650,HOU vs. MEM,0022500662,2026-01-26,Houston Rockets,Memphis Grizzlies,108,99
64653,CHI vs. LAL,0022500661,2026-01-26,Chicago Bulls,Los Angeles Lakers,118,129
64657,PHX vs. BKN,0022500669,2026-01-27,Phoenix Suns,Brooklyn Nets,106,102
64661,UTA vs. LAC,0022500670,2026-01-27,Utah Jazz,LA Clippers,103,115
64666,DEN vs. DET,0022500668,2026-01-27,Denver Nuggets,Detroit Pistons,107,109
64670,OKC vs. NOP,0022500667,2026-01-27,Oklahoma City Thunder,New Orleans Pelicans,104,95
64673,PHI vs. MIL,0022500666,2026-01-27,Philadelphia 76ers,Milwaukee Bucks,139,122
64678,NYK vs. SAC,0022500665,2026-01-27,New York Knicks,Sacramento Kings,103,87
64682,WAS vs. POR,0022500664,2026-01-27,Washington Wizards,Portland Trail Blazers,115,111